<%@include file="../share/directives.jsp"%>

<%
  ArrayList vecOrg = new ArrayList();
  vecOrg=(ArrayList)hshValues.get("vecValues");
  String strDate =(String)hshValues.get("txtDate");
  String strGen =(String)hshValues.get("genby");
  	
%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script>
var outlabel="<%= hshValues.get("labels")%>";
var textlabel="";
var datalen ="<%= vecOrg.size()%>";
function printpreview()
{
	if (datalen > 0)
   	{
	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=900,height=450,left=60,top=40");
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("<link rel='stylesheet' href='<%=ApplicationParams.getAppUrl()%>css/report.css' type='text/css'>");
	win.document.write("</head>");
	win.document.write("<body >");

	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><B><center>Organisation Details </center></B></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");

	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><B>Generated By :</B></TD>");
	win.document.write("<TD >"+'<%=strGen%>'+"</TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><B>Generated On :</B></TD>");
	win.document.write("<TD >"+'<%=strDate%>'+"</TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");
	win.document.write("<div id='top'>");
    win.document.write("<center><TABLE border='0' cellspacing='0' cellpadding='0' >");
		var agln="";
			
		 textlabel =outlabel.split(',');
		 for(l=0;l<textlabel.length;l++)
			{
				win.document.write("<td width='11%' height='30'> ");
				win.document.write("<div align='center'><B>"+ textlabel[l] + "</B></div>");
				win.document.write("</td>");
			}
				
			
			
			<%if (vecOrg.size() > 0)
			{
				for(int i1=0;i1<vecOrg.size();i1++)
				{
				  ArrayList vecVal = new ArrayList();
				  vecVal =(ArrayList)vecOrg.get(i1);
			 %>
				  
				  win.document.write("</tr>");
			<%	  for(int j1=1;j1<vecVal.size();j1++)
				  { 
						String stp =(String)vecVal.get(j1);
						if (stp.equals(" "))
						{
							stp="&nbsp;";
						}
             %>
					win.document.write("<td width='20%'align='left'>"+"<%=stp%>"+'&nbsp;'+"</td> ");	
			<%	  }
			%>
				  win.document.write("</tr>");
			<%	}
			}
			%>
		win.document.write("</TABLE></center>");
		win.document.write("</div>");
		win.document.write("</body>");
		win.document.write("</html>");
	}
}


function printData()
{

	if (datalen > 0)
   	{
   
	textlabel =outlabel.split(',');
		
		 for(l=0;l<textlabel.length;l++)
			{
				document.write("<td width='11%' height='30'> ");
				document.write("<div align='center'><B>"+ textlabel[l] + "</B></div>");
				document.write("</td>");
				
			}
			
	}
   else
	{
	   document.write("<tr><td align='center'>No Data Found</td></tr>");
	}		
         <%
		  for(int i=0;i<vecOrg.size();i++)
		  {
			  ArrayList ht = new ArrayList();
			  ht =(ArrayList)vecOrg.get(i);

			  String dt1 = (String)ht.get(0);
			  if (dt1.equalsIgnoreCase("C"))
			  {
				  dt1 = "Corporate";
			  }
			  else if (dt1.equalsIgnoreCase("R"))
			  {
				  dt1 = "Region";
			  }
			  else if (dt1.equalsIgnoreCase("D"))
			  {
				  dt1 = "District";
			  }
			  else if (dt1.equalsIgnoreCase("A"))
			  {
				  dt1 = "Area";
			  }
			  else if (dt1.equalsIgnoreCase("B"))
			  {
				  dt1 = "Branch";
			  }
		  %>
			   /* document.write("<tr>");
				document.write("<td height = '30' align='left'>");
				document.write("<div align='left'><b>"+")<!--<%=dt1%>-->" + "</b></div>");
					document.write("</td>");
				document.write("</tr>");*/
				document.write("<tr>");
		   <%	for(int j=1;j<ht.size();j++)
			    {
					String dt = (String)ht.get(j);
					if (dt.equals(" "))
					{%>
						
						dt="&nbsp;";
						
				<%		
					}
					
					
					//System.out.println("dt===================="+dt);
					
			%>		
				document.write("<td  height = '30' align='left'>");
					document.write("<div width='20' align='left'>"+"<%=dt%>"+'&nbsp;'+ "</div>");
					document.write("</td>");
					
					
			<%	}%>
				document.write("</tr>");					
		  <%}
		%>
}


</script>
<link rel="stylesheet" href="<%=ApplicationParams.getAppUrl()%>css/style.css" type="text/css">
<script language="JavaScript1.2" src="<%=ApplicationParams.getAppUrl()%>js/share/rightclick.js"></script>
<script language="JavaScript1.2" src="<%=ApplicationParams.getAppUrl()%>js/share/keytrap.js"></script>
</head>
<body >

<br>

<form name= "orgfrm" method="post" class="normal">
<h3><center> Organisation Details</center></h3>
<div class="cellContainer">
  
    
          <table class="outertable border1" width="100%" border="0" cellspacing="0" cellpadding="0" >
            <script>
         
			printData();
 		</script>
          </table>
        </td>
      </tr>
    </table>
  </div>
<br>
  <table class="outertable border1" border="0" cellspacing="0" cellpadding="0"   align="center">
    <tr> 
      <td > 
        <table class="outertable" width="100%" border="0" cellspacing="0" cellpadding="2">
          <tr> 
            <td > 
              <div align="center"> 
                <input type="button" name="Button232253" value="&lt;&lt; Previous" class="buttonothers" onClick="window.close()">
              </div>
            </td>
            <td > 
              <div align="center"> 
                <input type="button" name="Button2322532" value="Print Preview" class="buttonothers" onclick="printpreview()">
              </div>
            </td>
            <td> 
              <div align="center"> 
                <input type="button" name="rpclose" value="Close" class="buttonClose" onClick="window.close()">
              </div>
            </td>
          </tr>
        </table>
      </td>
      </tr>
      </table>
      <br>
</form>
</body>
</html>
