<%@ page import="com.sai.laps.helper.*,java.util.*" %>
<%@ taglib prefix ="laps"  uri="/WEB-INF/laps.tld" %>
<jsp:useBean id="hshValues" class="java.util.HashMap" scope="request" />
<laps:handleerror />

<%
  String align="left";
  String strVal="";
  ArrayList vecOrg = new ArrayList();
  vecOrg=(ArrayList)hshValues.get("vecValues");
  HashMap ht = null;
%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script>
var outlabel="<%= hshValues.get("labels")%>";
var textlabel="";
var userid ="<%=(String)hshValues.get("genby")%>";
var curdate ="<%=(String)hshValues.get("txtDate")%>";
var datalen ="<%= vecOrg.size()%>";

function printData()
{
   if (datalen > 0)
   {
		textlabel =outlabel.split(',');
		 for(l=0;l<textlabel.length;l++)
		 {
			document.write("<td class='dataheader' width='11%' height='30'> ");
			document.write("<div align='center'><B>"+ textlabel[l] + "</B></div>");
			document.write("</td>");
		}
   }
   else
	{
	   document.write("<tr><td align='center'>No Data Found</td></tr>");
	}
  <%

		  for(int i=0;i<vecOrg.size();i++)
		  {
			  ht = new HashMap();
			  ht =(HashMap)vecOrg.get(i);
			  strVal = (String)ht.get("prd_desc");
         %>
		  		document.write("<tr class='datagrid'>");
				writeData("left","<%=strVal%>");
			<%  if (ht.containsKey("prd_rng_from"))
				{
				strVal = (String)ht.get("prd_rng_from");
			%>
				writeData("right","<%=strVal%>");
			<%  
				}
				if (ht.containsKey("prd_rng_to"))
				{
				strVal = (String)ht.get("prd_rng_to");
			%>
				 writeData("right","<%=strVal%>");
			<%  }
				if (ht.containsKey("prd_flowpoint"))
				{
				strVal = (String)ht.get("prd_flowpoint");
			%>
				 writeData("center","<%=strVal%>");
			<%  }
				if (ht.containsKey("prd_maxclass"))
				{
				strVal = (String)ht.get("prd_maxclass");
			%>
				 writeData("center","<%=strVal%>");
			<%  }
				if (ht.containsKey("wrk_flowname"))
				{
				strVal = (String)ht.get("wrk_flowname");%>
				 writeData("left","<%=strVal%>");
			<%  }
				if (ht.containsKey("wrk_flowtype"))
				{
				strVal = (String)ht.get("wrk_flowtype");%>
				 writeData("left","<%=strVal%>");
			<%  }
				if (ht.containsKey("prd_duration"))
				{
					strVal = (String)ht.get("prd_duration");
			%>
					writeData("center","<%=strVal%>");
			 <%}%>
				document.write("</tr>");	

								
		  <%}
		  %>
			
}

function writeData(aln,val)
{
	
	document.write("<td height = '30' align='"+aln+"'");
	document.write("<div >"+val+ "</div>");
	document.write("</td>");
	
}
function printpreview()
{
	if (datalen > 0)
   	{
	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=600,height=450,left=60,top=40");
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("</head>");
	win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");

	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='4' face='MS Sans Serif'><B><center>Product Flowpoint Report </center></B></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");

	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><B>Generated By :</B></TD>");
	win.document.write("<TD >"+userid+"</TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><B>Generated On :</B></TD>");
	win.document.write("<TD >"+curdate+"</TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");

    win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='0' >");
		var agln="";
			
		 textlabel =outlabel.split(',');
      
		 for(l=0;l<textlabel.length;l++)
			{
				win.document.write("<td width='11%' height='30'> ");
				win.document.write("<div align='center'><B>"+ textlabel[l] + "</B></div>");
				win.document.write("</td>");
			}
				win.document.write("<tr>"); 
				win.document.write("</tr>"); 
			
		<%for(int i=0;i<vecOrg.size();i++)
		  {
			  
			  ht = new HashMap();
			  ht =(HashMap)vecOrg.get(i);
			  strVal = (String)ht.get("prd_desc");
         %>
		  		win.document.write("</tr>");
				win.document.write("<td width='20%'align='left'><%=strVal%></td> ");	
			<%  if (ht.containsKey("prd_rng_from"))
				{
				strVal = (String)ht.get("prd_rng_from");
			%>
				win.document.write("<td width='20%'align='right'><%=strVal%></td> ");	
			<%  
				}
				if (ht.containsKey("prd_rng_to"))
				{
				strVal = (String)ht.get("prd_rng_to");
			%>
				 win.document.write("<td width='20%'align='right'><%=strVal%></td> ");	
			<%  }
				if (ht.containsKey("prd_flowpoint"))
				{
				strVal = (String)ht.get("prd_flowpoint");
			%>
				 win.document.write("<td width='20%'align='center'><%=strVal%></td> ");	
			<%  }
				if (ht.containsKey("prd_maxclass"))
				{
				strVal = (String)ht.get("prd_maxclass");
			%>
				 win.document.write("<td width='20%'align='center'><%=strVal%></td> ");	
			<%  }
				if (ht.containsKey("wrk_flowname"))
				{
				strVal = (String)ht.get("wrk_flowname");%>
				 win.document.write("<td width='20%'align='left'><%=strVal%></td> ");	
			<%  }
				if (ht.containsKey("wrk_flowtype"))
				{
				strVal = (String)ht.get("wrk_flowtype");%>
				 win.document.write("<td width='20%'align='left'><%=strVal%></td> ");	
			<%  }
				if (ht.containsKey("prd_duration"))
				{
					strVal = (String)ht.get("prd_duration");
			%>
					win.document.write("<td width='20%'align='center'><%=strVal%></td> ");	
			 <%}%>
				win.document.write("</tr>");
			<%}%>
				win.document.write("</TABLE></center>");
				win.document.write("</body>");
				win.document.write("</html>");
	}
}

function previous()
{
	window.close();
}
</script>
<script language="JavaScript1.2" src="<%=ApplicationParams.getAppUrl()%>js/share/rightclick.js"></script>
<script language="JavaScript1.2" src="<%=ApplicationParams.getAppUrl()%>js/share/keytrap.js"></script>
</head>
<link rel="stylesheet" href="<%=ApplicationParams.getAppUrl()%>css/style.css" type="text/css">
<body>

<br>

<form name= "orgfrm" method="post" class="normal">
<h3><center> Product Flowpoint Report</center></h3>
<div class="cellContainer">
  
    <table class="outertable border1" width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
      <tr> 
        <td height="3"> 
          <table class="outertable border1" width="100%" border="0" cellspacing="0" cellpadding="0" >
            <script>
         
			printData();
 		</script>
          </table>
        </td>
      </tr>
    </table>
  </div>
<br>
  <table class="outertable border1" width="20%" border="0" cellspacing="0" cellpadding="2"  align="center">
    <tr> 
      <td> 
        
              <div align="center"> 
                <input type="button" name="Button232253" value="&lt;&lt; Previous" class="buttonothers" onClick="previous()">
              </div>
            </td>
            <td width="55%"> 
              <div align="center"> 
                <input type="button" name="Button2322532" value="Print Preview" class="buttonothers" onclick="printpreview()">
              </div>
            </td>
             <td width="21%"> 
              <div align="center"> 
                <input type="button" name="rpclose" value="Close" class="buttonClose" onClick="window.close()">
              </div>
           
      </td>
    </tr>
  </table>
  <br>
</form>
</body>
</html>
