<%@ page import="com.sai.laps.helper.*"%>
<%@ page import="java.util.ArrayList"%>
<%@ page import="java.util.HashMap"%>
<jsp:useBean id="hshValues" class="java.util.HashMap" scope="request" />
<html>
	<head>
	<!--  <style>
#top{background-color: #ffffff;}
#top table{ border-collapse: collapse;}
#top td {border: 0.5pt solid #6A6A6A; FONT-SIZE: 12px; COLOR: #000000; LINE-HEIGHT: 16px; FONT-FAMILY: "Arial"}

#top1{background-color: #ffffff;}
#top1 td {border: 0 solid #6A6A6A; FONT-SIZE: 12px; COLOR: #000000; LINE-HEIGHT: 16px; FONT-FAMILY: "Arial"}

	</style>-->
	<title>LAPS</title>
	<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>
	</head>
	<body bgcolor='#FFFFFF' text='#000000' leftmargin='0' topmargin='0' marginwidth='0' marginheight='0'>
	<form name= 'orgfrm' method='post'>
	<div id='top'>
 	<table width='100%' border='0' cellspacing='0' cellpadding='3'>
    <tr>
    <td align='center'><img src='<%=ApplicationParams.getAppUrl()%>img/bank_rep_logo.jpg'></td>       		
    </tr>
    <tr> 
    <td align='center'><strong>Karnataka Bank Ltd.</strong></td>
    </tr>
    <tr> 
    <td align='center'><%=Helper.correctNull((String)session.getAttribute("strOrgName"))%></td>
    </tr>
    <tr> 
    <td align='center'> Target Master Report </td>
    </tr>
    </table>
	<TABLE border='0' width='100%'>
	<TR>
	<TD width='20%' align='right'><font size='1' face='MS Sans Serif'><B>Generated By :</B></font></TD>
	<TD width='30%'><font size='1' face='MS Sans Serif'><%=session.getAttribute("strUserName")%></font></TD>
	<TD width='20%' align='right'><font size='1' face='MS Sans Serif'><B>Branch :</B></font></TD>
	<TD width='30%'><font size='1' face='MS Sans Serif'><%=hshValues.get("branch").toString() %></font></TD>
	</TR>
	<TR>
	<TD width='20%' align='right'><font size='1' face='MS Sans Serif'><B>Generated On :</B></font></TD>
	<TD width='30%'><font size='1' face='MS Sans Serif'><%=Helper.getCurrentDateTime()%></font></TD>
	<TD width='20%' align='right'><font size='1' face='MS Sans Serif'><B>Period :</B></font></TD>
	<TD width='30%'><font size='1' face='MS Sans Serif'><%=hshValues.get("period").toString() %></font></TD>
	</TR>
	
	<TR>
	<TD > </TD>
	<TD > </TD>
	</TR>
	<TR>
	<TD > </TD>
	<TD > </TD>
	</TR>
	<TR>
	<TD > </TD>
	<TD > </TD>
	</TR>
	<tr>
    <td colspan='4' align='center'>
    <b> Note : All Amounts are in Lakhs </b>
    </td>
    </tr>
	</TABLE>
	<div >
    <span id="top"><table width='100%' border='0' cellspacing='0' cellpadding='0' align='center'  >
    <tr> 
    <td height='3'> 
    <div >
    <table width='100%' border='1' cellspacing='0' cellpadding='3' bordercolor='#eeeeee'>
    <tr>
    <td>
	<div align='center'><font size='1' face='MS Sans Serif'><B>&nbsp;</B></font></div>
	</td>
	<td colspan='2'>
	<div align='center'><font size='1' face='MS Sans Serif'><B>Target</B></font></div>
	</td>
	<td colspan='2'>
	<div align='center'><font size='1' face='MS Sans Serif'><B>Sanctioned</B></font></div>
	</td>
	<td colspan='2'>
	<div align='center'><font size='1' face='MS Sans Serif'><B>Outstanding</B></font></div>
	</td>
	</tr>
	
	<tr>
	<td>
	<div align='center'><font size='1' face='MS Sans Serif'><B>&nbsp;</B></font></div>
	</td>
	<td>
	<div align='center'><font size='1' face='MS Sans Serif'><B>No of Accounts</B></font></div>
	</td>
	<td>
	<div align='center'><font size='1' face='MS Sans Serif'><B>Amount</B></font></div>
	</td>
	<td>
	<div align='center'><font size='1' face='MS Sans Serif'><B>No of Accounts</B></font></div>
	</td>
	<td>
	<div align='center'><font size='1' face='MS Sans Serif'><B>Amount</B></font></div>
	</td>
	<td>
	<div align='center'><font size='1' face='MS Sans Serif'><B>No of Accounts</B></font></div>
	</td>
	<td>
	<div align='center'><font size='1' face='MS Sans Serif'><B>Amount</B></font></div>
	</td>
	</tr>
	
	<%
		ArrayList arrcol=new ArrayList();
		ArrayList arrcalculated=null;
		ArrayList arrrow=null;
		arrrow=(ArrayList)hshValues.get("branchtarget");
		arrcalculated=(ArrayList)hshValues.get("calculated_targets");
		ArrayList arraydesc=new ArrayList(3);
		if(arrrow.size()>0)
		{
	%>
	
	<%
		int i=0,j=0;
		arraydesc.add("Total Deposits");
		arraydesc.add("Gross Advances");
		arraydesc.add("Export Advances");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'>
				<b>Priority Sector Advances </b>
			</font></div>
		</td>
		<td colspan="6">
			&nbsp;
		</td>	
	</tr>
	
	<%
		int count_calculated=0;
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; Agriculture</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Direct");
		arraydesc.add("Indirect");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; MSME Enterprises</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Direct");
		arraydesc.add("Indirect");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; MSME Manufacturing</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Micro");
		arraydesc.add("Small");
		arraydesc.add("Medium");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; MSME Services</b></font></div>
		</td>
	</tr>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; &nbsp; &nbsp; Micro</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; &nbsp; &nbsp; W/W</b></font></div>
		</td>
	</tr>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Road Transport Operator");
		arraydesc.add("Small Business");
		arraydesc.add("Retail Trade");
		arraydesc.add("Prof. & Self Employees");
		arraydesc.add("Others");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; &nbsp; &nbsp; Small</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; &nbsp; &nbsp; W/W</b></font></div>
		</td>
	</tr>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Road Transport Operator");
		arraydesc.add("Small Business");
		arraydesc.add("Retail Trade");
		arraydesc.add("Prof. & Self Employees");
		arraydesc.add("Others");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Khadi & Village Industries");
		arraydesc.add("Medium");
		arraydesc.add("Indirect");
		arraydesc.add("NBFC (Manufacturing & Service)");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; Total Indirect MSME</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Micro Credit");
		arraydesc.add("SCS/STS State Sponsored Organisations");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; Union Education</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Rural & Semi-Urban Areas");
		arraydesc.add("Urban Areas");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp; Union Home</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Rural & Semi-Urban Areas");
		arraydesc.add("Urban Areas");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Union Trade");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp;Total Of Priority Sector</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'><b>Retail Lending</b></font></div>
		</td>
	</tr>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Union Education");
		arraydesc.add("Union Home");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp;Union Comfort</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("i) Clean");
		arraydesc.add("ii) Secured");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp; &nbsp; &nbsp; <%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Union Miles");
		arraydesc.add("Union Health");
		arraydesc.add("Union Smile");
		arraydesc.add("Union Cash");
		arraydesc.add("Union Mortgage");
		arraydesc.add("Union Shares");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'><b>GOVT. SPONSORED SCHEMES</b></font></div>
		</td>
	</tr>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("P. M. R. Y.");
		arraydesc.add("P.M.E.G.P.");
		arraydesc.add("S.G.S.Y.");
		arraydesc.add("S.J.S.R.Y.");
		arraydesc.add("G.J.R.H.F.S.");
		arraydesc.add("S.L.R.S.");
		arraydesc.add("S.R.M.S.");
		arraydesc.add("U.L.U.C.C.");
		arraydesc.add("U.A.C.C.");
		arraydesc.add("S.C.C.");
		arraydesc.add("SCP / Scheme by SC/ST Corporation (Excluding SLRS)");
		arraydesc.add("S.A.C.P.");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'><b>WEAKER SECTION</b></font></div>
		</td>
	</tr>
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Small & Marginal Farmers");
		arraydesc.add("Village & Cottage Industries");
		arraydesc.add("SGSY Beneficiaries");
		arraydesc.add("SC/ST Beneficiaries");
		arraydesc.add("DRI Beneficiaries");
		arraydesc.add("SJSRY Beneficiaries");
		arraydesc.add("SLRS / SRMS Beneficiaries");
		arraydesc.add("Self Help Groups");
		arraydesc.add("Loans to Distressed Poor");
		arraydesc.add("Minority Communities");
		arraydesc.add("Women Beneficiaries");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'><b>NPA</b></font></div>
		</td>
	</tr>
	
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Op. Balance as on Beginning Of Period");
		arraydesc.add("Cash Recovery");
		arraydesc.add("Upgradation");
		arraydesc.add("Write off");
		arraydesc.add("Slippage");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	
	<tr>
		<td>
			<div align='left'><font size='1' face='MS Sans Serif'><b>NPA</b></font></div>
		</td>
	</tr>
	
	<%
		arrcol=new ArrayList();
		arrcol=(ArrayList)arrcalculated.get(count_calculated);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'><b>&nbsp; &nbsp;NPA as on End of Period</b></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		count_calculated++;
		arrcol=null;
	%>
	
	
	<%
		arraydesc=new ArrayList();
		arraydesc.add("Recovery in Written- off A/cs");
		arraydesc.add("Profit");
		arraydesc.add("Non Interest Income");
		arraydesc.add("Non Interest Expenditure");
		for(i=0;i<arraydesc.size();i++)
		{
			arrcol=new ArrayList();
			arrcol=(ArrayList)arrrow.get(j);
	%>
	<tr>
	<td>
	<div align='left'><font size='1' face='MS Sans Serif'>&nbsp; &nbsp;<%=arraydesc.get(i)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(0)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(1)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(2)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(3)%></font></div>
	</td>
	<td>
	 <div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(4)%></font></div>
	</td>
	<td>
	<div align='right'><font size='1' face='MS Sans Serif'><%=arrcol.get(5)%></font></div>
	</td>
	</tr>
	<%
		j++;
		arrcol=null;
		}
		arraydesc=null;
	%>
	<%
		}
		else
		{
	%>
	<tr>
		<td colspan="7" align="center">
			<font size='1' face='MS Sans Serif'><b>No Data Found</b></font>
		</td>
	</tr>
	
	<%
		}
	%>
	</TABLE></div></td></tr></table></span></div></div></form>
	</BODY>
	</HTML>