<%@ page import="com.sai.laps.helper.*,java.util.*" %>
<%@ taglib prefix ="laps"  uri="/WEB-INF/laps.tld" %>
<jsp:useBean id="hshValues" class="java.util.HashMap" scope="request" />
<laps:handleerror />

<%
  ArrayList vecOrg = new ArrayList();
  vecOrg=(ArrayList)hshValues.get("vecValues");
  String align="left";
  	
%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script>
var outlabel="<%= hshValues.get("labels")%>";
var textlabel="";
var per="<%= hshValues.get("txtDate")%>";
var datalen ="<%= vecOrg.size()%>";
var outcount ="<%= hshValues.get("count")%>";
function printpreview()
{
	if (datalen > 0)
   	{
	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=600,height=450,left=60,top=40");
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("</head>");
	win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");

	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='4' face='MS Sans Serif'><B><center>Applicant Statuswise Summary Report</center></B></font></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");

	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated By :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("genby")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated On :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("txtSaveDate")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Period :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("txtDate")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");

    win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='3' bordercolor='#eeeeee'>");
		var agln="";
			
		 textlabel =outlabel.split(',');
		 for(l=0;l<textlabel.length;l++)
			{
				win.document.write("<td width='11%' height='30'> ");
				win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ textlabel[l] + "</B></font></div>");
				win.document.write("</td>");
			}
				win.document.write("<tr>"); 
				win.document.write("</tr>"); 
			
			
			<%if (vecOrg.size() > 0)
			{
				String strtemp="";
				for(int i1=0;i1<vecOrg.size();i1++)
				{
				  ArrayList vecVal = new ArrayList();
				  vecVal =(ArrayList)vecOrg.get(i1);
			 %>
				  
				  win.document.write("</tr>");
			<%	  for(int j1=0;j1<vecVal.size();j1++)
				  { 
				if(j1==0)
		   		{
		   			String stp = (String)vecVal.get(j1);		
		   			align =(String)vecVal.get(j1+1);
					if (!(stp.trim().equals("")) && !(strtemp.trim().equals(stp)))
					{
						strtemp =stp;
		   		%>			   			
		   			win.document.write("<td height = '30' colspan='4' align='<%=align%>'>");
		   			win.document.write("<div align='<%=align%>'>&nbsp;<font size='1' face='MS Sans Serif'><b>"+"<%=stp%>" + "&nbsp;</b></font></div>");
					win.document.write("</td></tr>");
		   			win.document.write("<tr>");
		   			
		   		<%}
		   		}
		   		else
		   		{
				
					String stp = (String)vecVal.get(j1);
					align =(String)vecVal.get(j1+1);
					if (stp.equals(" "))
					{
						stp="&nbsp;";
					}
             %>
					win.document.write("<td width='20%'align='<%=align%>'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=stp%>"+'&nbsp;'+"</td> ");	
			<%	
				  }
			j1=j1+1; 
				}
			%>
				  win.document.write("</tr>");
			<%	}
			}
			%>
		win.document.write("</TABLE></center>");
		
		win.document.write("</body>");
		win.document.write("</html>");
	}
}

function printData()
{
	if (datalen > 0)
   	{
	textlabel =outlabel.split(',');
		 for(l=0;l<textlabel.length;l++)
			{
				document.write("<td width='11%' height='30'> ");
				document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ textlabel[l] + "</B></font></div>");
				document.write("</td>");
			}
	}
   else
	{
	   document.write("<tr><td align='center'>No Data Found</td></tr>");
	}	
         <%
         String strtemp="";
		  for(int i=0;i<vecOrg.size();i++)
		  {
			  ArrayList ht = new ArrayList();
			  ht =(ArrayList)vecOrg.get(i);
		  %>
				document.write("<tr>");
		   <%	for(int j=0;j<ht.size();j++)
			    {
		   		if(j==0)
		   		{
		   			String dt = (String)ht.get(j);		
		   			align =(String)ht.get(j+1);
					if (!(dt.trim().equals("")) && !(strtemp.trim().equals(dt)))
					{
						strtemp =dt;
		   		%>			   			
		   			document.write("<td height = '30' colspan='4' align='<%=align%>'>");
		   			document.write("<div align='<%=align%>'>&nbsp;<font size='1' face='MS Sans Serif'><b>"+"<%=dt%>" + "&nbsp;</b></font></div>");
					document.write("</td></tr>");
		   			document.write("<tr>");
		   			
		   		<%}
		   		}
		   		else
		   		{
					String dt = (String)ht.get(j);
					align =(String)ht.get(j+1);
					if (dt.trim().equals(""))
					{
						dt="&nbsp;";
					}		
		%>			document.write("<td height = '30' align='<%=align%>'>");
					document.write("<div align='<%=align%>'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=dt%>" + "&nbsp;</font></div>");
					document.write("</td>");
				
		<%	   }
		   	j= j+1;
			   
		   }%>
				document.write("</tr>");					
		  <%}
		%>
}

function menuOptionDivMouseDown (url) {
		//if (! isMac) {
			document.currentMenu.style.display='none';
			document.currentMBarOpt.style.border='1px solid lightgrey';
			document.menuIsActive = false;
			//window.location=url;
			document.forms[0].action=url;
			document.forms[0].submit();
			//}
		}
</script>
</head>

<body bgcolor="#EEEAE3" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<br>
<h3><center>Applicant Statuswise Summary Report</center></h3>
<form name= "orgfrm" method="post">

<div class="cellContainer">
  
    <table width="100%" border="1" cellspacing="0" cellpadding="0" bordercolorlight="#8F8369" bordercolordark="#FFFFFB" align="center">
      <tr> 
        <td height="3"> 
          <table width="100%" border="1" cellspacing="0" cellpadding="0"  bordercolor="#FFFFFF">
            <script>
         
			printData();
 		</script>
          </table>
        </td>
      </tr>
    </table>
	
  </div>
<br>
  <table border="1" cellspacing="0" cellpadding="0"  bordercolorlight="#8F8369" bordercolordark="#FFFFFB" align="center">
    <tr> 
      <td height="17"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="2">
          <tr> 
            <td width="45%"> 
              <div align="center"> 
                <input type="button" name="Button232253" value="&lt;&lt; Previous" style="background-color:#8F8369;font-weight:bold;color:white;font-size=10;font-family:mssansserif;width:80;font-weight:bold" onClick="window.close()">
              </div>
            </td>
            <td width="55%"> 
              <div align="center"> 
                <input type="button" name="Button2322532" value="Print Preview" style="background-color:#8F8369;font-weight:bold;color:white;font-size=10;font-family:mssansserif;width:100;font-weight:bold" onclick="printpreview()">
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</form>
</body>
</html>
