<%@ page import="com.sai.laps.helper.*,java.util.*" %>
<%@ taglib prefix ="laps"  uri="/WEB-INF/laps.tld" %>
<jsp:useBean id="hshValues" class="java.util.HashMap" scope="request" />
<laps:handleerror />

<%
  ArrayList vecOrg = new ArrayList();
  vecOrg=(ArrayList)hshValues.get("vecValues");
  String align="left";
  String align1="left";
  int kk=0;
   int kkd=0;
  	
%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script>
var outlabel="<%= hshValues.get("labels")%>";
//var outlabel1="<%= hshValues.get("labels")%>";
var per="<%= hshValues.get("txtDate")%>";
var textlabel="";
var textlabel1="";


var datalen ="<%= vecOrg.size()%>";
function printpreview()
{
	if (datalen > 0)
   	{
	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=600,height=450,left=60,top=40");
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("</head>");
	win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");

	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='4' face='MS Sans Serif'><B><center>Portfolio Management</center></B></font></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");
				
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated By :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("genby")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated On :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("txtSaveDate")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Period :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("txtDate")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");

    win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='5' width='100%'>");


		var agln="";
	// taken from -->
	
	
	textlabel =outlabel.split(",");
				   
						win.document.write("<tr>");
						for(l1=0;l1<textlabel.length;l1++)
						{
							win.document.write("<td width='4%' height='30'> ");
							if(l1==0)
							{
								win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B> S.No </B></font></div>");
							}
							else
							{
								win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ textlabel[l1] + "</B></font></div>");
							}
							win.document.write("</td>");
						}
						win.document.write("</tr>");

			   <%
			 String strPPreOrg="";
			String strPCurOrg="";
		  for(int i1=0;i1<vecOrg.size();i1++)
		  {
			  ArrayList ht1 = new ArrayList();
			  ht1 =(ArrayList)vecOrg.get(i1);
				//out.println("ht==="+ht);
			
		  %>
   

		   <%	for(int j1=0;j1<ht1.size();j1++)
			    {
					strPCurOrg =	(String)ht1.get(0);
					if(!strPPreOrg.equals(strPCurOrg))
					{
						strPPreOrg =strPCurOrg;
						kkd= 1;
						%>
						win.document.write("<tr><td colspan=5 align='center'><font size='1' face='MS Sans Serif'><B><%=strPCurOrg%></B></font></td></tr>");
						
						<%
				}
					String dt1="";
					if(j1!=0)
					{
						dt1 = (String)ht1.get(j1);
						align =(String)ht1.get(j1+1);
						if (dt1.equals(" "))
						{
							dt1="&nbsp;";
						}
					}
					else
					{
						dt1= Integer.toString(kkd++);
						align="left";
					}
					
			%>		
								
					win.document.write("<td height = '30' align='<%=align%>'>");
					win.document.write("<div align='<%=align%>'><font size='1' face='MS Sans Serif'>"+"<%=dt1%>" + "</font></div>");
					win.document.write("</td>");
					
			<%	j1= j1+1;
				}%>
				win.document.write("</tr>");
		 //----------------
			<%	
			}
			%>
		
		win.document.write("</TABLE></center>");
		win.document.write("</body>");
		win.document.write("</html>");
	}
}

function printData()
{
	if (datalen > 0)
   	{
textlabel =outlabel.split(",");
					document.write("<tr>");

				for(l=0;l<textlabel.length;l++)
				{
			
					document.write("<td width='4%' height='30'> ");
					if(l==0)
					{
						document.write("<div align='center'><font size='1' face='MS Sans Serif'><B> S.No</B></font></div>");
					}
					else
					{
						document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ textlabel[l] + "</B></font></div>");
					}
					document.write("</td>");

				}
					document.write("</tr>");
  

         <%
			 String strPreOrg="";
			String strCurOrg="";
		  for(int i=0;i<vecOrg.size();i++)
		  {
			  ArrayList ht = new ArrayList();
			  ht =(ArrayList)vecOrg.get(i);
	 //out.println("ht==="+ht);
			
		  %>
   

		   <%	for(int j=0;j<ht.size();j++)
			    {
					strCurOrg =	(String)ht.get(0);
			if(!strPreOrg.equals(strCurOrg))
			{
				strPreOrg =strCurOrg;
				kk= 1;
				%>
				document.write("<tr><td colspan=5 align='center'><font size='1' face='MS Sans Serif'><B><%=strCurOrg%></B></font></td></tr>");
/*				textlabel =outlabel.split(",");
				for(l=0;l<textlabel.length;l++)
				{
					document.write("<tr>");
			
					document.write("<td width='11%' height='30'> ");
					if(l==0)
					{
						document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ S.No + "</B></font></div>");
					}
					else
					{
						document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ textlabel[l] + "</B></font></div>");
					}
					document.write("</td></tr>");

				}
*/				document.write("<tr>");
			<%
			}
					String dt="";
					if(j!=0)
					{
						dt = (String)ht.get(j);
						align =(String)ht.get(j+1);
							if (dt.equals(" "))
							{
								dt="&nbsp;";
							}
					}
					else
					{
						dt= Integer.toString(kk++);
						align="left";
					}
					
			%>		
								
			document.write("<td height = '30' align='<%=align%>'>");
					document.write("<div align='<%=align%>'><font size='1' face='MS Sans Serif'>"+"<%=dt%>" + "</font></div>");
					document.write("</td>");
					
			<%	j= j+1;
				}%>
				document.write("</tr>");					
		  <%}
		%>
			}
   else
	{
	   document.write("<tr><td align='center'>No Data Found</td></tr>");
	}	
}


</script>
</head>

<body bgcolor="#EEEAE3" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<br>
<h3><center>Portfolio Management</center></h3>
<form name= "orgfrm" method="post">

<div class="cellContainer">
  
    <table width="100%" border="1" cellspacing="0" cellpadding="5" bordercolorlight="#8F8369" bordercolordark="#FFFFFB" align="center">
      <tr> 
        <td height="3"> 
		<table width="100%" border="0" cellspacing="0" cellpadding="0" bordercolor="#FFFFFF">
		  <tr><td>
          <table width="100%" border="1" cellspacing="0" cellpadding="5" bordercolor="#FFFFFF">
		  <tr><td>
            <script>
         
			printData();
 		</script>	 </td></tr>
          </table>
		  </td></tr>
		  </table>
        </td>
      </tr>
    </table>
  </div>
<br>
  <table border="1" cellspacing="0" cellpadding="0"  bordercolorlight="#8F8369" bordercolordark="#FFFFFB" align="center">
    <tr> 
      <td height="17"> 
        <table width="100%" border="0" cellspacing="0" cellpadding="2">
          <tr> 
            <td width="45%"> 
              <div align="center"> 
                <input type="button" name="Button232253" value="&lt;&lt; Previous" style="background-color:#8F8369;font-weight:bold;color:white;font-size=10;font-family:mssansserif;width:80;font-weight:bold" onClick="window.close()">
              </div>
            </td>
            <td width="55%"> 
              <div align="center"> 
                <input type="button" name="Button2322532" value="Print Preview" style="background-color:#8F8369;font-weight:bold;color:white;font-size=10;font-family:mssansserif;width:100;font-weight:bold" onclick="printpreview()">
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</form>
</body>
</html>
