<%@ page import="com.sai.laps.helper.*,java.util.*" %>
<%@ taglib prefix ="laps"  uri="/WEB-INF/laps.tld" %>
<jsp:useBean id="hshValues" class="java.util.HashMap" scope="request" />
<laps:handleerror />

<%
  ArrayList vecOrg = new ArrayList();
  vecOrg=(ArrayList)hshValues.get("vecValues");
   String align="left";
  ArrayList vecVal=null;
  	
%>


<html>
<head>
<title>Report - SOAR</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script>
var outlabel="<%= hshValues.get("labels")%>";
var textlabel="";
var datalen ="<%= vecOrg.size()%>";

function menuOptionDivMouseDown (url) {
		//if (! isMac) {
			document.currentMenu.style.display='none';
			document.currentMBarOpt.style.border='1px solid lightgrey';
			document.menuIsActive = false;
			//window.location=url;
			document.forms[0].action=url;
			document.forms[0].submit();
			//}
		}
</script>
</head>
<body bgcolor="#FFFFFF" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<div align="center"><font size="2"><b><font face="MS Sans Serif">Status of Application Received Report (SOAR)</font></b></font><br>
  <br>
</div>
<%
if (vecOrg.size() > 0)
{
%>
<br>
<table width="100%" border="0" cellspacing="0" cellpadding="2">
  <tr> 
    <td width="12%"><font size="1" face="MS Sans Serif"><b>Organisation</b></font></td>
    <td width="38%"><font size="1" face="MS Sans Serif"><%=(String)hshValues.get("OrgName")%></font></td>
    <td width="16%"><b><font size="1" face="MS Sans Serif">Generated By</font></b></td>
    <td width="34%"><font size="1" face="MS Sans Serif"><%=(String)hshValues.get("genby")%></font></td>
  </tr>
  <tr> 
    <td width="12%"><font size="1" face="MS Sans Serif"><b>Period</b></font></td>
    <td width="38%"><font size="1" face="MS Sans Serif"><%=(String)hshValues.get("txtDate")%></font></td>
    <td width="16%"><b><font size="1" face="MS Sans Serif">Generated On</font></b></td>
    <td width="34%"><font size="1" face="MS Sans Serif"><%=(String)hshValues.get("txtSaveDate")%></font></td>
  </tr>
 
</table>

<table width="100%" border="0" cellspacing="0" cellpadding="5" bordercolorlight="#EBEBF8" bordercolordark="#82829F" height="182">
  
      <table width="100%" border="0" cellspacing="1" cellpadding="2">
        <%
int grandtot=0;
int grandtot1=0;
int grandtot2=0;
int grandtot3=0;
String subtot="0";
String subtot1="0";
String subtot2="0";
String subtot3="0";
int prdcode=0;
HashMap hshsub= new HashMap();

 for (int i=0;i<vecOrg.size();i++)
  {  
	  
	  vecVal = new ArrayList();
	  vecVal =(ArrayList)vecOrg.get(i);
	  if (i==0)
	  {
%>
        <tr> 
          <td colspan="4" height="57"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="3">
				
              <tr> 
                <td width="16%"><font size="1" face="MS Sans Serif"><b>Category</b></font></td>
                <td width="84%"><font size="1" face="MS Sans Serif"><%=(String)vecVal.get(2)%></font></td>
              </tr>
              <tr> 
                <td width="16%"><font size="1" face="MS Sans Serif"><b>Sub Category</b></font></td>
                <td width="84%"><font size="1" face="MS Sans Serif"><%=(String)vecVal.get(3) %></font><font size="1" face="MS Sans Serif"></font><font size="1" face="MS Sans Serif"></font></td>
              </tr>
            </table>
          </td>
        </tr>
		<%}%>
        <br>
       
            
		<%	if (i==0)
			{%>
			 <tr> 
          <td colspan="4"> 
              <tr bgcolor="#E2E2E2" > 
                <td width="23%" align="center" height="25"> <font color="#000000"><b><font face="MS Sans Serif" size="1">Product</font></b></font></td>
                <td width="18%" align="center" height="25"> <font color="#000000"><b><font size="1" face="MS Sans Serif">No 
                  of Loans Applied</font></b></font></td>
                <td width="21%" align="center" height="25"> <font color="#000000"><b><font size="1" face="MS Sans Serif">No 
                  of loans Sanctioned</font></b></font></td>
                <td width="19%" align="center" height="25"><b><font face="MS Sans Serif" size="1" color="#000000">No 
                  of Loans Rejected</font></b></td>
                <td width="19%" height="25"> 
                  <div align="center"><font color="#000000"><b><font size="1" face="MS Sans Serif">No 
                    of Loans in Process</font></b></font></div>
                </td>
              </tr>
			 
			
			 <%}%>
			
              <tr > 
                <td width="23%" align="left"><font size="1" face="MS Sans Serif"><%=(String)vecVal.get(1)+" "+(String)vecVal.get(4)+"-"+(String)vecVal.get(5)%></font></td>
                <td width="17%" align="center"><font size="1" face="MS Sans Serif"><%=(String)vecVal.get(7)%></font></td>
                <td width="20%" align="center"><font size="1" face="MS Sans Serif"><%=(String)vecVal.get(8)%></font></td>
                <td width="19%" align="center"><font size="1" face="MS Sans Serif"><%=(String)vecVal.get(9)%></font></td>
                <td width="21%" align="center"><font size="1" face="MS Sans Serif"><%=(String)vecVal.get(10)%></font></td>
              </tr>
           
          
        <%
}//for
%>
 <tr> 
          <td width="22%" height="20" align="center"><b><font size="1" face="MS Sans Serif"> 
            Total : </font></b></td>
          <td width="17%" height="20" align="center"><b><font size="1" face="MS Sans Serif"><%=hshValues.get("grandtot")%></font></b></td>
          <td width="20%" align="center" height="20"><b><font size="1" face="MS Sans Serif"><%=hshValues.get("grandtot1")%></font></b></td>
          <td width="22%" height="20" align="center"><b><font size="1" face="MS Sans Serif"><%=hshValues.get("grandtot2")%></font></b></td>
          <td width="19%" height="20" align="center"><b><font size="1" face="MS Sans Serif"><%=hshValues.get("grandtot3")%></font></b></td>
  </tr>
</table>


</table>
<%
}
else
{
%>
<h2>
  <center>
    No Data Found
</center>
</h2>
<%}
%>
<br>
</body>
</html>

