<%@ include file="../share/directives.jsp"%>

<%
	ArrayList arrCol = null;
	ArrayList arrRow  =  (ArrayList)hshValues.get("arrRow");
 %>
 <html>
 <head>
 <title>LAPS</title>
<link rel="stylesheet"
	href="<%=ApplicationParams.getAppUrl()%>css/report.css"
	type="text/css">
 
<script>

var AppUrl="<%=ApplicationParams.getAppUrl()%>";
function doPrintPreview()
{
	<%if (arrRow.size()> 0){%>

	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=800,height=450,left=60,top=40");
	
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("<link rel='stylesheet'	href='<%=ApplicationParams.getAppUrl()%>css/report.css'	type='text/css'>");
	win.document.write("</head>");
	
	win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");
	
	win.document.write("<table width='100%' border='0' cellspacing='0' cellpadding='3'>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><img src='"+'<%=ApplicationParams.getAppUrl()%>'+"img/kbl_newlogo.jpg'"+"></td>");          		
	win.document.write("</tr>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><b>"+'<%=Helper.correctNull((String)hshValues.get("branch_name"))%>'+"</b></td>");
	win.document.write("</tr>");
	win.document.write("</table>");
        
	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><strong><center> MSME Applications Reporting format from "+'<%=Helper.correctNull((String)hshValues.get("strFromDate")) %>'+" to " +'<%=Helper.correctNull((String)hshValues.get("strToDate")) %>'+"</center></strong></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");
	
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated By :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)hshValues.get("genby"))%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");
	
	win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='1' bordercolor='#eeeeee' width='230%' >");
	var agln="";
	win.document.write("<TR>");
	win.document.write("<TD rowspan='2' width='5%' nowrap>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Sl No" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2'width='8%' nowrap>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Branch Code" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Branch Name " +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='8%' nowrap>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Region Code" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Region Name" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"District" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"State" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Name of the Applicant" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Application Reference No" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Date of Application" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Purpose of Loan" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD width='10%' colspan='2'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Limit Sought (Customer)" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD width='10%' colspan='2'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Limit Proposed (Bank)" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	/*win.document.write("<TD rowspan='2' width='20%' nowrap>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Invalid Application - "+'<br>'+"Stages - 8th day/11th day "+'<br>'+"/21st day " +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'nowrap>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Date when Application"+'<br>'+" became Invalid" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");*/
	win.document.write("<TD rowspan='2' width='10%' nowrap>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Date of Upload"+'<br>'+" to LAPS" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Proposal ID" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Status of the application" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Sanction Date" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD rowspan='2' width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Rejection Date " +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("</TR>");
			
	win.document.write("<TR>");	
	win.document.write("<TD width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Fund Based" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD width='10%' nowrap>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Non Fund"+'<br>'+" Based" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD width='10%'>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Fund Based" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("<TD width='10%' nowrap>");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Non Fund"+'<br>'+"Based" +'&nbsp;'+ "</font></div>");
	win.document.write("</TD >");
	win.document.write("</TR>");	

	 <%
     if(arrRow != null && arrRow.size()>0){
     for(int i=0;i<arrRow.size();i++){
   	arrCol = (ArrayList)arrRow.get(i);
   	if(arrCol!=null && arrCol.size()>0){%>
   	win.document.write("<TR align='center'>");	
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=i+1%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(0))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='left'>");
   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(1))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(2))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='left' nowrap>");
   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(3))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='left' nowrap>");
   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(16))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='left'>");
   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(17))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='left' nowrap>");
   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(4))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(5))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(6))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(7))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='right'>");
   	win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(8))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='right'>");
   	win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(9))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='right'>");
   	win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(10))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD align='right'>");
   	win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(11))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
    //win.document.write("<TD>");
   	//win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%//=Helper.correctNull((String)arrCol.get(18))%>' +'&nbsp;'+ "</font></div>");
   	//win.document.write("</TD >");
   	//win.document.write("<TD>");
   	//win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%//=Helper.correctNull((String)arrCol.get(19))%>' +'&nbsp;'+ "</font></div>");
   	//win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(12))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(13))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(20))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(14))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("<TD>");
   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(15))%>' +'&nbsp;'+ "</font></div>");
   	win.document.write("</TD >");
   	win.document.write("</TR>");	
    <% }}}%>
    win.document.write("<TR>");
	win.document.write("</TABLE></center>");

	win.document.write("<TABLE border='0' width='225%' align='right' height='150px' valign='middle'>");
	
	win.document.write("<TR>");
	win.document.write("<TD align='right'><font size='1' face='MS Sans Serif'>Authorised Signatory </font></TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");
	
	win.document.write("</body>");
	win.document.write("</html>");
	<%}%>
}
function doClose()
{
	window.close();
}
</script>
</head>

<body  text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<form name= "orgfrm" method="post">
  <table width="100%" border="0" cellspacing="0" cellpadding="3">

    <tr> 
      <td align="center"><img src="<%=ApplicationParams.getAppUrl()%>img/kbl_newlogo.jpg"></td>
    </tr>
    <tr> 
      <td align="center"><b> <%=Helper.correctNull((String)hshValues.get("branch_name")) %></b> 
    </tr>
    <tr> 
      <td align="center"><b>MSME Applications Reporting format from <%=Helper.correctNull((String)hshValues.get("branch_name")) %> to  <%=Helper.correctNull((String)hshValues.get("branch_name")) %></b></td>
    </tr>
  </table>

	
  <table width="230%" border="0" cellspacing="0" cellpadding="1" align="center" bordercolor='#eeeeee'>
    <tr align="center"> 
      <td rowspan=2 valign="top" width="5%"><b>Sl.No</b></td>
      <td rowspan=2 valign="top" width="8%" nowrap="nowrap"><b>Branch Code</b></td>
      <td rowspan=2 valign="top" width="10%" nowrap="nowrap"> 
        <b>Branch Name</b>
      </td>
      <td   rowspan=2 valign="top" width="8%" nowrap="nowrap">  
        <b>Region Code</b>
      </td>
      <td  rowspan=2 align="center" valign="top" width="18%" nowrap="nowrap"><b>Region Name</b></td>
      <td   rowspan=2 valign="top" width="15%" nowrap="nowrap"> 
       <b>District</b>
      </td>
      <td rowspan=2 valign="top" width="10%" > 
       <b>State</b>
      </td>
      <td   rowspan=2 valign="top" width="10%" nowrap="nowrap"> 
        <b>Name of the Applicant</b>
      </td>
      <td   rowspan=2 valign="top" width="10%"> 
        <b>Application Reference No</b>
      </td>
      <td   rowspan=2 valign="top" width="10%"> 
        <b>Date of Application</b>
      </td>
      <td   rowspan=2 valign="top" width="10%"> 
        <b>Purpose of Loan</b>
      </td>
      <td   valign="top" colspan=2 width="10%" nowrap="nowrap"> 
        <b>Limit Sought (Customer)</b>
      </td>
      <td   valign="top" colspan=2 width="10%" nowrap="nowrap"> 
        <b>Limit Proposed (Bank)</b>
      </td><!--
      <td   rowspan=2 valign="top" width="20%" nowrap="nowrap"> 
        <b>Invalid Application  <br> - Stages - 8th day /<br>11th day / 21st day</b>
      </td>
      <td   rowspan=2 valign="top" width="10%" nowrap="nowrap"> 
        <b>Date <br>when Application<br> became Invalid</b>
      </td>
      --><td   rowspan=2 valign="top" width="10%" nowrap="nowrap"> 
        <b>Date of Upload<br> to LAPS</b>
      </td>
      <td   rowspan=2 valign="top" width="10%" nowrap="nowrap"> 
        <b>Proposal ID</b>
      </td>
      <td   rowspan=2 valign="top" width="10%" nowrap="nowrap"> 
        <b>Status of the <br>Application</b>
      </td>
      <td   rowspan=2 valign="top" width="10%" nowrap="nowrap"> 
        <b>Sanction Date</b>
      </td>
      <td   rowspan=2 valign="top" width="10%" nowrap="nowrap"> 
        <b>Rejection Date</b>
      </td>
    </tr>
    <tr>
	    <td  width="10%"><b>Fund Based</b></td>
	    <td  width="10%"><b>Non Fund Based</b></td>
	    <td  width="10%"><b>Fund Based</b></td>
	    <td  width="10%"><b>Non Fund Based</b></td>
    </tr>
    <%
      if(arrRow != null && arrRow.size()>0){
    	  for(int i=0;i<arrRow.size();i++){
    		  arrCol = (ArrayList)arrRow.get(i);
    	 
    %>
    <tr align="center"> 
      <td ><%=i+1%>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(0)) %>&nbsp;</td>
      <td align="left"><%=Helper.correctNull((String)arrCol.get(1)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(2)) %>&nbsp;</td>
      <td align="left" nowrap="nowrap"><%=Helper.correctNull((String)arrCol.get(3))%>&nbsp;</td>
      <td align="left" nowrap="nowrap"><%=Helper.correctNull((String)arrCol.get(16))%>&nbsp;</td>
      <td align="left" nowrap="nowrap"><%=Helper.correctNull((String)arrCol.get(17))%>&nbsp;</td>
      <td align="left"><%=Helper.correctNull((String)arrCol.get(4)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(5)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(6)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(7)) %>&nbsp;</td>
      <td align="right"><%=Helper.correctNull((String)arrCol.get(8)) %>&nbsp;</td>
      <td align="right"><%=Helper.correctNull((String)arrCol.get(9)) %>&nbsp;</td>
      <td align="right"><%=Helper.correctNull((String)arrCol.get(10)) %>&nbsp;</td>
      <td align="right"><%=Helper.correctNull((String)arrCol.get(11)) %>&nbsp;</td>
      <!--<td ><%=Helper.correctNull((String)arrCol.get(18)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(19)) %>&nbsp;</td>
      --><td ><%=Helper.correctNull((String)arrCol.get(12)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(13)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(20)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(14)) %>&nbsp;</td>
      <td ><%=Helper.correctNull((String)arrCol.get(15)) %>&nbsp;</td>
    </tr>
    <%}}else{ %>
    <tr> 
      <td colspan="22"> 
        <div align="center">No Data Found</div>
      </td>
    </tr>
    <%} %>
  </table>

	<br>
	<lapschoice:combuttonnew btnnames="Print Preview" btnenable='<%=Helper.correctNull((String)request.getParameter("btnenable"))%>' />  
</form>
</body>
</html>
