<%@include file="../share/directives.jsp"%>

<%
	ArrayList arrCol = null;
	ArrayList arrRow  =  (ArrayList)hshValues.get("arrRow");
	
	java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
	nf.setGroupingUsed(false);
	nf.setMinimumFractionDigits(2);
	nf.setMaximumFractionDigits(2);
 %>
 <html>
 <head>
 <title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet"
	href="<%=ApplicationParams.getAppUrl()%>css/report.css"
	type="text/css">
 
<script>

var AppUrl="<%=ApplicationParams.getAppUrl()%>";
var per="<%= hshValues.get("txtDate")%>";
function doClose()
{
	window.close();
}
function doPrintPreview()
{
	<%if (arrRow.size()> 0){%>

		win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=800,height=450,left=60,top=40");
		
		win.document.write("<head>");
		win.document.write("<title>LAPS</title>");
		win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
		win.document.write("<link rel='stylesheet'	href='<%=ApplicationParams.getAppUrl()%>css/report.css'	type='text/css'>");
		win.document.write("</head>");
		
		win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");
		
		win.document.write("<table width='100%' border='0' cellspacing='0' cellpadding='3'>");
		win.document.write("<tr>");
		win.document.write("<td align='center'><img src='"+'<%=ApplicationParams.getAppUrl()%>'+"img/kbl_newlogo.jpg'"+"></td>");          		
		win.document.write("</tr>");
		win.document.write("<tr>");
		win.document.write("<td align='center'><b>"+'<%=Helper.correctNull((String)hshValues.get("branch_name"))%>'+"</b></td>");
		win.document.write("</tr>");
		win.document.write("</table>");
	        
		win.document.write("<center>");
		win.document.write("<TABLE border='0'>");
		win.document.write("<TR>");
		win.document.write("<TD width='20%'><strong><center>Pool based Rating Report for " +'<%=Helper.correctNull((String)hshValues.get("hidStatus")) %>'+" Proposal "+"</center></strong></TD>");
		win.document.write("</TABLE>");
		win.document.write("</center>");
		
		win.document.write("<TABLE border='0'>");
		win.document.write("<TR>");
		win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated By :</B></font></TD>");
		win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)hshValues.get("genby"))%>'+"</font></TD>");
		win.document.write("</TR>");
		win.document.write("<TR>");
		win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Period:</B></font></TD>");
		win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+per+"</font></TD>");
		win.document.write("</TR>");
		win.document.write("<TR>");
		win.document.write("<TD > </TD>");
		win.document.write("<TD > </TD>");
		win.document.write("</TR>");
		win.document.write("<TR>");
		win.document.write("<TD > </TD>");
		win.document.write("<TD > </TD>");
		win.document.write("</TR>");
		win.document.write("<TR>");
		win.document.write("<TD > </TD>");
		win.document.write("<TD > </TD>");
		win.document.write("</TR>");
		win.document.write("</TABLE>");
		
		win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='3' bordercolor='#eeeeee' width='95%' >");
		var agln="";
		win.document.write("<TR>");
		win.document.write("<TD rowspan='2' width='5%' nowrap>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Sl No" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD rowspan='2'width='10%' nowrap>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Sol ID" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD rowspan='2' width='10%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Customer ID" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD rowspan='2' width='20%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Borrower Name" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD rowspan='2' width='20%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Proposal No" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD rowspan='2' width='10%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Module" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD rowspan='2' width='10%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Status" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD colspan='3' width='30%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)hshValues.get("hidStatus")) %>'+" At" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD rowspan='2' width='15%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Date Received" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("</TR>");
				
		win.document.write("<TR>");	
		win.document.write("<TD width='10%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"User ID" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD width='10%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Name" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("<TD width='10%'>");
		win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"Department" +'&nbsp;'+ "</font></div>");
		win.document.write("</TD >");
		win.document.write("</TR>");	

		 <%
	      if(arrRow != null && arrRow.size()>0){
	      for(int i=0;i<arrRow.size();i++){
	    	arrCol = (ArrayList)arrRow.get(i);
	    	if(arrCol!=null && arrCol.size()>0){%>
	    	win.document.write("<TR>");	
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=i+1%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(0))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(1))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(2))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(3))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(9))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(4))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(5))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(6))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(7))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("<TD>");
	    	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'<%=Helper.correctNull((String)arrCol.get(8))%>' +'&nbsp;'+ "</font></div>");
	    	win.document.write("</TD >");
	    	win.document.write("</TR>");	
	     <% }%>
	      <%if(i==arrRow.size()-1) {%>
	      win.document.write("<TR>");	
	      win.document.write("<TD colspan='10' align='left'>");
	      win.document.write("<div><font size='1' face='MS Sans Serif'>"+" Total No of Applications :"+'<%=i+1%>' +'&nbsp;'+ "</font></div>");
	      win.document.write("</TD >");
	      win.document.write("</TR>");	
	    	<%}}}else{ %>
	    	 win.document.write("<TR>");	
		      win.document.write("<TD>");
		      win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+" No Record Found "+'&nbsp;'+ "</font></div>");
		      win.document.write("</TD >");
		      win.document.write("</TR>");
	    <%} %>
		win.document.write("</TABLE></center>");
		win.document.write("</body>");
		win.document.write("</html>");
		<%}%>
}
</script>
</head>

<body  text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<form name= "orgfrm" method="post">
  <table width="100%" border="0" cellspacing="0" cellpadding="3">

    <tr> 
      <td align="center"><img src="<%=ApplicationParams.getAppUrl()%>img/kbl_newlogo.jpg"></td>
    </tr>
    <tr> 
      <td align="center"><b> <%=Helper.correctNull((String)hshValues.get("branch_name")) %></b> 
    </tr>
    <tr> 
      <td align="center"><b>Pool based Rating Report for <%=Helper.correctNull((String)hshValues.get("hidStatus")) %> Proposal</b></td>
    </tr>
  </table>

  <table width="98%" border="1" cellspacing="0" cellpadding="3" align="center" bordercolor='#eeeeee'>
    <tr align="center"> 
      <td  width="5%" rowspan=2 valign="top" nowrap="nowrap"><b>Sr No</b></td>
      <td  width="12%" rowspan=2 valign="top"> 
        <div align="center"><b>Sol ID</b></div>
      </td>
      <td  width="8%" rowspan=2 valign="top"><b>Customer ID</b></td>
       <td width="20%" rowspan=2 valign="top"> 
        <div align="center"><b>Borrower Name</b></div>
      </td>
      <td width="15%" rowspan=2 valign="top"> 
        <div align="center"><b>Proposal No</b></div>
      </td>
      <td  width="10%" rowspan=2 valign="top"> 
        <div align="center"><b>Module</b></div>
      </td>
      <td  width="10%" rowspan=2 valign="top"> 
        <div align="center"><b>Status</b></div>
      </td>
      <td  colspan="3" align="center" valign="top" ><b><%=Helper.correctNull((String)hshValues.get("hidStatus")) %> at</b></td>
      <td  width="27%" rowspan=2 valign="top"> 
        <div align="center"><b>Date received</b></div>
      </td>
    </tr>
    <tr align="center"> 
      <td width="11%" height="2"> 
        <div align="center"><b>User ID </b></div>
      </td>
      <td width="9%" height="2"> 
        <div align="center"><b>Name</b></div>
      </td>
      <td width="9%" height="2"> 
        <div align="center"><b>Department</b></div>
      </td>
    </tr>
    <%
      if(arrRow != null && arrRow.size()>0){
      for(int i=0;i<arrRow.size();i++){
    		  arrCol = (ArrayList)arrRow.get(i);
    		  if(arrCol!=null && arrCol.size()>0){%>
    	  <tr>
    	  <td align="center"><%=i+1 %>&nbsp;</td>
    	  <td align="center"><%=Helper.correctNull((String)arrCol.get(0)) %>&nbsp;</td>
    	  <td align="center"><%=Helper.correctNull((String)arrCol.get(1)) %>&nbsp;</td>
    	  <td><%=Helper.correctNull((String)arrCol.get(2)) %>&nbsp;</td>
    	  <td align="center"><%=Helper.correctNull((String)arrCol.get(3)) %>&nbsp;</td>
    	  <td align="center"><%=Helper.correctNull((String)arrCol.get(9)) %>&nbsp;</td>
    	  <td align="center"><%=Helper.correctNull((String)arrCol.get(4)) %>&nbsp;</td>
    	  <td align="center"><%=Helper.correctNull((String)arrCol.get(5)) %>&nbsp;</td>
    	  <td><%=Helper.correctNull((String)arrCol.get(6)) %>&nbsp;</td>
    	  <td><%=Helper.correctNull((String)arrCol.get(7)) %>&nbsp;</td>
    	  <td align="center"><%=Helper.correctNull((String)arrCol.get(8)) %>&nbsp;</td>
    	  </tr>
     <% }%>
      <%if(i==arrRow.size()-1) {%>
      <tr><td colspan="10"><b>Total No of Applications : <%=i+1 %></b></td></tr>
    	<%}}}else{ %>
    <tr> 
      <td colspan="11"> 
        <div align="center">No Data Found</div>
      </td>
    </tr>
    <%} %>
  </table>

	  
 
  <br>
  <lapschoice:combuttonnew btnnames="Print Preview" btnenable='<%=Helper.correctNull((String)request.getParameter("btnenable"))%>' />
</form>
</body>
</html>
