<%@ include file="../../share/directives.jsp"%>
<%@ taglib prefix ="laps"  uri="/WEB-INF/laps.tld" %>
<%@ page import="com.sai.laps.helper.*"%>
<%@ page import="com.sai.laps.helper.*,java.util.*"%>
<%@ taglib prefix="lapschoice" uri="/WEB-INF/laps.tld"%>
<lapschoice:handleerror />
<%
    ArrayList arrRow=new ArrayList();
    ArrayList arrCol=new ArrayList();
    arrRow=(ArrayList)hshValues.get("arrRow");
    int intsize=0,intsize1=0;

String align="left";
int arrsize=0; 
if(arrRow !=null)
{
 arrsize=arrRow.size();
 intsize=arrRow.size();
}
java.text.NumberFormat jtn=java.text.NumberFormat.getInstance();
jtn.setMaximumFractionDigits(2);
jtn.setMinimumFractionDigits(2);
jtn.setGroupingUsed(false);
String str_report = Helper.correctNull((String) request.getParameter("report"));


%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet"	href="<%=ApplicationParams.getAppUrl()%>css/style.css"	type="text/css">
<script>
var report = "<%=str_report%>";
var outlabel="<%= hshValues.get("labels")%>";
var textlabel="";
var datalen ="<%= arrRow.size()%>";
function doClose()
		{
			window.close();
		}

function printData()
		{
			if (datalen > 0)
		   	{
				document.write("<tr>");
				document.write("<td width='8' height='30'> ");
				document.write("<div align='center'><B> S.No </B></div>");
				document.write("</td>");
				document.write("<td width='8' height='30'> ");
				document.write("<div align='center' nowrap><B>Valuer Name</B></div>");
				document.write("</td>");
				document.write("<td width='8' height='30'> ");
				document.write("<div align='center' nowrap><B>Security Owner CustomerId</B></div>");
				document.write("</td>");
				document.write("<td width='8' height='30'> ");
				document.write("<div align='center' nowrap><B>Security OwnerName</B></div>");
				document.write("</td>");
				document.write("<td width='8' height='30'> ");
				document.write("<div align='center' nowrap><B>Security Classification</B></div>");
				document.write("</td>");
				document.write("<td width='8' height='30'> ");
				document.write("<div align='center' nowrap><B>Net Security Value</B></div>");
				document.write("</td>");
				document.write("<td width='8' height='30'> ");
				document.write("<div align='center' nowrap><B>Branch Name</B></div>");
				document.write("</td>");
				document.write("</tr>");

							<% if (arrRow!=null && arrRow.size() > 0)
								{
									for(int i=0;i<arrRow.size();i++)
									 { 
										  arrCol = new ArrayList();
									 	  arrCol =(ArrayList)arrRow.get(i);
									 	%>
			         		document.write("<tr>");
			         		document.write("<td width='8%'align='left'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(0)%>"+'&nbsp;'+"</td>");
			             	document.write("<td width='8%'align='left'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(1)%>"+'&nbsp;'+"</td>");
			    			document.write("<td width='8%'align='left'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(2)%>"+'&nbsp;'+"</td>");
			    			document.write("<td width='8%'align='left'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(3)%>"+'&nbsp;'+"</td>");
			    			document.write("<td width='8%'align='left'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(4)%>"+'&nbsp;'+"</td>");
			    			document.write("<td width='8%'align='left'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(5)%>"+'&nbsp;'+"</td>");
			    			document.write("<td width='8%'align='left'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(6)%>"+'&nbsp;'+"</td>");
			    			document.write("</tr>");
			         		<%	} } %>
			}
			else
			{
				 document.write("<tr><td align='center'>No Data Found</td></tr>");
			}

			document.write("<table>");
			document.write("<tr>");
			document.write("<td><B>Total Applications = "+'<%=intsize%>');
			document.write("</B></td>");
			document.write("</tr>");
			document.write("</table>");
			}         
		         
</script>
				
<link rel="stylesheet"	href="<%=ApplicationParams.getAppUrl()%>css/style.css"	type="text/css">
</head>

<body>
<div align="center">
<h3></h3></div>
<table width="100%" border="0" cellspacing="0" cellpadding="3" class="outertable">
        <tr>
          <td align="center"><img src="<%=ApplicationParams.getAppUrl()%>img/kbl_newlogo.jpg"></td>          		
        </tr>
        <tr> 
          <td align="center"><strong>Karnataka Bank Ltd.</strong></td>
        </tr>
       <tr> 
          <td align="center"><b>Data Valuation Report Generation </b></td>
        </tr>
       <tr>
        <td align="center"><b>Generated By :<%=Helper.correctNull((String)hshValues.get("genby"))%> </b></td>
        </tr>
        <tr>
        <td align="center"><b>Generated On :  <%=Helper.getCurrentDateTime()%></b></td>
        </tr> 
                 
    </table>
    
<form name="custdet" method="post" class="normal">
          <table width="100%"border="0" cellspacing="0" cellpadding="3" class="outertable border1" >
            <script>         
			printData();
 		</script>
          </table>
</form>
</body>
</html>
