<%@ include file="../../share/directives.jsp"%>
<%@ taglib prefix ="laps"  uri="/WEB-INF/laps.tld" %>
<%ArrayList ArrRow=new ArrayList();
ArrayList ArrCol=new ArrayList();
ArrRow=(ArrayList)hshValues.get("ArrValues");
ArrayList ArrSolRow=(ArrayList)hshValues.get("ArrRow");
ArrayList ArrKpowRow=(ArrayList)hshValues.get("ArrKpowerRow");
int arrsize=0,arrSolsize=0,arrKpowersize=0;
if(ArrRow !=null)
{
	arrsize=ArrRow.size();
}
if(ArrSolRow!=null)
arrSolsize=ArrSolRow.size();
if(ArrKpowRow!=null)
	arrKpowersize=ArrKpowRow.size();
java.text.NumberFormat jtn=java.text.NumberFormat.getInstance();
jtn.setMaximumFractionDigits(2);
jtn.setMinimumFractionDigits(2);
jtn.setGroupingUsed(false);
%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script>
function doPrintPreview()
{
	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=800,height=450,left=60,top=40");
	
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("<link rel='stylesheet'	href='<%=ApplicationParams.getAppUrl()%>css/report.css'	type='text/css'>");
	win.document.write("</head>");
	
	win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");
	
	win.document.write("<table width='100%' border='0' cellspacing='0' cellpadding='3'>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><img src='"+'<%=ApplicationParams.getAppUrl()%>'+"img/kbl_newlogo.jpg'"+"></td>");          		
	win.document.write("</tr>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><b>"+'<%=Helper.correctNull((String)hshValues.get("Org_Name"))%>'+"</b></td>");
	win.document.write("</tr>");
	
	win.document.write("<tr>");
	win.document.write("<td>");        
	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><strong><center> Limit Sanction Resolution Register for the period of "+'<%=Helper.correctNull((String)hshValues.get("strFromDate"))%>'+" - "+' <%=Helper.correctNull((String)hshValues.get("strToDate"))%>'+"</center></strong></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");
	win.document.write("</td>");
	win.document.write("</tr>");

	win.document.write("<tr>");
	win.document.write("<td>");   
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated By :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=session.getAttribute("strUserName")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated On :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("txtSaveDate")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");
	win.document.write("</td>");   
	win.document.write("</tr>");
	

	win.document.write("<tr>");
	win.document.write("<td>");   
	win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='3' bordercolor='#eeeeee' >");
	win.document.write("<tr>"); 
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sno" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Branch" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Reference Number & Date" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap'  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Name and Address of Borrower/Co-obligant/Guarantor" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature of Business" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Constitution" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' width='200px'  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Purpose of Advance" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Networth" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "NWC <br>(in lakhs)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Project Cost in Case of TL" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1' colspan='5'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Prime & Collateral  Security" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ " Security Coverage </br>(%)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature of Facility & Bank Schematic Code - Amount" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Applicable Rate of Interest / Commission" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sanctioned Rate of Interest / Commission" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Periods" + "</br>"+"(Months)"+"</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Repayment Mode" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Total Liability of Borrower" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("</tr>"); 
	win.document.write("<tr>"); 
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sector" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Rating" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Type" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Security Amount" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Margin  </br>(%)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Date of Valuation" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("</tr>"); 
	<%
	ArrayList arrvalRowPrint=new ArrayList();
          ArrayList arrvalColPrint=new ArrayList();
          ArrayList arrvalNewPrint=new ArrayList();
          int arrsizeprint=0,q=0,p=0;
          if(arrsize>0){
          for(p=0;p<arrsize;p++)
      		{
        	  ArrCol = (ArrayList) ArrRow.get(p);
      		%>
      		win.document.write("<tr>"); 
      		win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=p+1 %>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(13))%>" +'&nbsp;'+ "</font></div><br>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(0))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%String strname="";
      		String strAppName=(String)ArrCol.get(1); 
      		String[] strNameArr=strAppName.split("~");
      		int strArrlen=strNameArr.length;
      		for(int k=0;k<strArrlen;k++)
      		{
      			strname=strNameArr[k];
      			String[] strAppDetails=strname.split("@");
      			String strType=strAppDetails[1];
      			if(strType.equalsIgnoreCase("a")){
          			strType="Applicant";
          		}else if(strType.equals("c")){
          			strType="Joint Applicant";
          		}else if(strType.equals("g")){
          			strType=" Guarantor";
          		}
          		else if(strType.equals("o")){
          			strType="Co-Obligant";
          		}
          		else if(strType.equals("CO")){
          			strType="Co-Obligant";
          		}
          		else if(strType.equals("G")){
          			strType="Guarantor";
          		}
          		else if(strType.equals("C")){
          			strType="Co-Applicant";
          		}
          		else{
          			strType="";
          		}%>
          		<%if(!strType.equalsIgnoreCase("")) {%>
          		win.document.write("<tr> ");
          		win.document.write("<td><u><b> ");
          		win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strType) %>"+'&nbsp;-&nbsp;'+"<%=Helper.correctNull((String)strAppDetails[0]) %>"+'&nbsp;'+ "</font></div>");
          		win.document.write("</b></u></td> ");
          		win.document.write("</tr> ");
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[2]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}else{%>
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[2]) %>"+'&nbsp;-&nbsp;'+"<%=Helper.correctNull((String)strAppDetails[0]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}%>
      			<%if(strType.equalsIgnoreCase("Applicant")){ %>
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[3]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}%>
          		<%
      		}
      			%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td rowspan='1'>");
			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(3))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='1'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(15))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%String strTemp="";
      		String strSecName=(String)ArrCol.get(4);
      		arrvalRowPrint=new ArrayList();
      		StringTokenizer st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(2)) %>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(20)) %>"+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(19))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(21);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(6);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(22);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%
      		arrvalRowPrint=new ArrayList();
            arrvalColPrint=new ArrayList();
      		String secval="";
      		String strSecVal=(String)ArrCol.get(7);
      		StringTokenizer st1 = new StringTokenizer(strSecVal,"~");
			while (st1.hasMoreTokens())
			{
				arrvalRowPrint.add(st1.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				secval = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td nowrap='nowrap'> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)secval) %>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(23);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(18))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(5);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td align='center' nowrap='nowrap' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(8);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td align='center' nowrap='nowrap' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(14);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(10);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%strTemp="";
      		strSecName=(String)ArrCol.get(9);
      		arrvalRowPrint=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRowPrint.add(st.nextToken());
			}
			arrsizeprint=arrvalRowPrint.size();
			for(q=0;q<arrsizeprint;q++)
      		{
				strTemp = (String) arrvalRowPrint.get(q);%>
        	  win.document.write("<tr> ");
        	  win.document.write("<td> ");
        	  win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strTemp )%>" +'&nbsp;'+ "</font></div>");
        	  win.document.write("</td> ");
        	  win.document.write("</tr> ");
        	 <%
      		}
      		%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(12))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
			win.document.write("<tr>"); 
			win.document.write("<td>");
			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(11))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(17))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
      		<%}}else{%>
      		win.document.write("<tr>"); 
      		win.document.write("<td  colspan='22'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+" - No Record Found -" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
      		<%}%>
	win.document.write("</TABLE></center>");
	win.document.write("</td>");   
	win.document.write("</tr>"); 
	
	win.document.write("<tr>");   
	win.document.write("<td>");     
	win.document.write("<TABLE border='0' cellspacing='0' cellpadding='3' width='100%'>");
	win.document.write("<tr>");		
	win.document.write("<td align='left'>");
	win.document.write("<b>Total Applications = &nbsp;</b>");
	win.document.write("<b>"+"<%=p%>" + "</b>");
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("<tr>");		
	win.document.write("<td align='left'>");
	win.document.write("<b>Total Sanctioned Amount = &nbsp;</b>");
	win.document.write("<b>"+"<%=Helper.correctNull((String)hshValues.get("sanctionamt"))%>" + "</b>");
	win.document.write("</td>");
	win.document.write("</tr>");


	win.document.write("<tr>");
	win.document.write("<td>");        
	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><strong><center>Solvency Sanctioned Application Report for the period of "+'<%=Helper.correctNull((String)hshValues.get("strFromDate"))%>'+" - "+' <%=Helper.correctNull((String)hshValues.get("strToDate"))%>'+"</center></strong></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");
	win.document.write("</td>");
	win.document.write("</tr>");


	win.document.write("<tr>");
	win.document.write("<td>");   
	win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='3' bordercolor='#eeeeee' >");
	win.document.write("<tr>"); 
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sno" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Branch" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Reference Number & Date" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap'  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Name and Address of Borrower/Co-obligant/Guarantor" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature of Business" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Constitution" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' width='200px'  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Purpose of Advance" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Networth" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "NWC <br>(in lakhs)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Project Cost in Case of TL" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1' colspan='5'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Prime & Collateral  Security" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ " Security Coverage </br>(%)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature of Facility & Bank Schematic Code - Amount" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Applicable Rate of Interest / Commission" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sanctioned Rate of Interest / Commission" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Periods" + "</br>"+"(Months)"+"</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Repayment Mode" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Total Liability of Borrower" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("</tr>"); 
	win.document.write("<tr>"); 
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sector" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Rating" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Type" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Security Amount" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Margin  </br>(%)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Date of Valuation" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("</tr>"); 
	<%
	p=0;
	if(arrSolsize>0){
          
          for(p=0;p<arrSolsize;p++)
      		{
        	  ArrCol = (ArrayList) ArrSolRow.get(p);
      		%>
      		win.document.write("<tr>"); 
      		win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=p+1 %>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(13))%>" +'&nbsp;'+ "</font></div><br>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(0))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%String strname="";
      		String strAppName=(String)ArrCol.get(1); 
      		String[] strNameArr=strAppName.split("~");
      		int strArrlen=strNameArr.length;
      		for(int k=0;k<strArrlen;k++)
      		{
      			strname=strNameArr[k];
      			String[] strAppDetails=strname.split("@");
      			String strType=strAppDetails[1];
      			if(strType.equalsIgnoreCase("a")){
          			strType="Applicant";
          		}
          		else{
          			strType="";
          		}%>
          		<%if(!strType.equalsIgnoreCase("")) {%>
          		win.document.write("<tr> ");
          		win.document.write("<td><u><b> ");
          		win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strType) %>"+'&nbsp;-&nbsp;'+"<%=Helper.correctNull((String)strAppDetails[0]) %>"+'&nbsp;'+ "</font></div>");
          		win.document.write("</b></u></td> ");
          		win.document.write("</tr> ");
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[2]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}else{%>
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[2]) %>"+'&nbsp;-&nbsp;'+"<%=Helper.correctNull((String)strAppDetails[0]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}%>
      			<%if(strType.equalsIgnoreCase("Applicant")){ %>
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[3]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}%>
          		<%
      		}
      			%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td rowspan='1'>");
			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(3))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='1'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(15))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(4))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(2)) %>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(20)) %>"+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(19))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(6))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(7))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(18))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(5))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(8))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(14))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(10))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(9))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(12))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
			win.document.write("<tr>"); 
			win.document.write("<td>");
			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(11))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(17))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
      		<%}}else{%>
      		win.document.write("<tr>"); 
      		win.document.write("<td  colspan='22'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+" - No Record Found -" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
      		<%}%>


	win.document.write("</TABLE></center>");
	win.document.write("</td>");   
	win.document.write("</tr>");

	win.document.write("<tr>");   
	win.document.write("<td>");     
	win.document.write("<TABLE border='0' cellspacing='0' cellpadding='3' width='100%'>");
	win.document.write("<tr>");		
	win.document.write("<td align='left'>");
	win.document.write("<b>Total Applications = &nbsp;</b>");
	win.document.write("<b>"+"<%=p%>" + "</b>");
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("<tr>");		
	win.document.write("<td align='left'>");
	win.document.write("<b>Total Sanctioned Amount = &nbsp;</b>");
	win.document.write("<b>"+"<%=Helper.correctNull((String)hshValues.get("dblsolsanctamt"))%>" + "</b>");
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("</TABLE>");
	win.document.write("</td>");   
	win.document.write("</tr>");



	win.document.write("<tr>");
	win.document.write("<td>");        
	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><strong><center>K-Power Sanctioned Application Report for the period of "+'<%=Helper.correctNull((String)hshValues.get("strFromDate"))%>'+" - "+' <%=Helper.correctNull((String)hshValues.get("strToDate"))%>'+"</center></strong></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");
	win.document.write("</td>");
	win.document.write("</tr>");


	win.document.write("<tr>");
	win.document.write("<td>");   
	win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='3' bordercolor='#eeeeee' >");
	win.document.write("<tr>"); 
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sno" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Branch" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Reference Number & Date" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap'  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Name and Address of Borrower/Co-obligant/Guarantor" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature of Business" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Constitution" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' width='200px'  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Purpose of Advance" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Networth" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "NWC <br>(in lakhs)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td  rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Project Cost in Case of TL" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='1' colspan='5'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Prime & Collateral  Security" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ " Security Coverage </br>(%)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature of Facility & Bank Schematic Code - Amount" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Applicable Rate of Interest / Commission" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sanctioned Rate of Interest / Commission" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Periods" + "</br>"+"(Months)"+"</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td nowrap='nowrap' rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Repayment Mode" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td rowspan='2'> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Total Liability of Borrower" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("</tr>"); 
	win.document.write("<tr>"); 
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sector" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Rating" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Type" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Nature" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Security Amount" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Margin  </br>(%)" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("<td> ");
	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Date of Valuation" + "</B></font></div>");
	win.document.write("</td>");
	win.document.write("</tr>"); 
	<%
          p=0;
	if(arrKpowersize>0){
          for(p=0;p<arrKpowersize;p++)
      		{
        	  ArrCol = (ArrayList) ArrKpowRow.get(p);
      		%>
      		win.document.write("<tr>"); 
      		win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=p+1 %>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(13))%>" +'&nbsp;'+ "</font></div><br>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(0))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<TABLE border='0'>");
			<%String strname="";
      		String strAppName=(String)ArrCol.get(1); 
      		String[] strNameArr=strAppName.split("~");
      		int strArrlen=strNameArr.length;
      		for(int k=0;k<strArrlen;k++)
      		{
      			strname=strNameArr[k];
      			String[] strAppDetails=strname.split("@");
      			String strType=strAppDetails[1];
      			if(strType.equalsIgnoreCase("a")){
          			strType="Applicant";
          		}
          		else{
          			strType="";
          		}%>
          		<%if(!strType.equalsIgnoreCase("")) {%>
          		win.document.write("<tr> ");
          		win.document.write("<td><u><b> ");
          		win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strType) %>"+'&nbsp;-&nbsp;'+"<%=Helper.correctNull((String)strAppDetails[0]) %>"+'&nbsp;'+ "</font></div>");
          		win.document.write("</b></u></td> ");
          		win.document.write("</tr> ");
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[2]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}else{%>
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div ><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[2]) %>"+'&nbsp;-&nbsp;'+"<%=Helper.correctNull((String)strAppDetails[0]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}%>
      			<%if(strType.equalsIgnoreCase("Applicant")){ %>
      			win.document.write("<tr> ");
      			win.document.write("<td> ");
      			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)strAppDetails[3]) %>" +'&nbsp;'+ "</font></div>");
      			win.document.write("</td> ");
      			win.document.write("</tr> ");
      			<%}%>
          		<%
      		}
      			%>
			win.document.write("</TABLE>");
			win.document.write("</td>");
			win.document.write("<td rowspan='1'>");
			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(3))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='1'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(15))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(4))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(2)) %>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(20)) %>"+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(19))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(6))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(7))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td  rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(18))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(5))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%//=Helper.correctNull((String)ArrCol.get(8))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(14))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(10))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td align='center' rowspan='2'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(9))%>"+'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			
			win.document.write("<td align='right' rowspan='2'>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(12))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
			win.document.write("<tr>"); 
			win.document.write("<td>");
			win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(11))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("<td>");
			win.document.write("<div align='right'><font size='1' face='MS Sans Serif'>"+"<%=Helper.correctNull((String)ArrCol.get(17))%>" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
      		<%}}else{%>
      		win.document.write("<tr>"); 
      		win.document.write("<td colspan='22'>");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+" - No Record Found -" +'&nbsp;'+ "</font></div>");
			win.document.write("</td>");
			win.document.write("</tr>"); 
      		<%}%>


	win.document.write("</TABLE></center>");
	win.document.write("</td>");   
	win.document.write("</tr>");

	win.document.write("<tr>");   
	win.document.write("<td>");     
	win.document.write("<TABLE border='0' cellspacing='0' cellpadding='3' width='100%'>");
	win.document.write("<tr>");		
	win.document.write("<td align='left'>");
	win.document.write("<b>Total Applications = &nbsp;</b>");
	win.document.write("<b>"+"<%=p%>" + "</b>");
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("<tr>");		
	win.document.write("<td align='left'>");
	win.document.write("<b>Total Sanctioned Amount = &nbsp;</b>");
	win.document.write("<b>"+"<%=Helper.correctNull((String)hshValues.get("dblkpowersanctamt"))%>" + "</b>");
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("</TABLE>");
	win.document.write("</td>");   
	win.document.write("</tr>");

	

	
	win.document.write("<tr>");		
	win.document.write("<td align='right'>");
	win.document.write("<b>Head of the Department / Office &nbsp;</b>");
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("<tr>");   
	win.document.write("<td>"+"&nbsp;"+"</br>"); 
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("<tr>");   
	win.document.write("<td>"+"&nbsp;"+"</br>"); 
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("<tr>");   
	win.document.write("<td>");     
	win.document.write("<TABLE border='0' cellspacing='0' cellpadding='3' width='100%'>");
	win.document.write("<tr>");		
	win.document.write("<td align='left'>");
	win.document.write("<b>Asst/Dy/General Manager &nbsp;</b>");
	win.document.write("</td>");
	win.document.write("<td align='center'>");
	win.document.write("<b>Chief General Manager &nbsp;</b>");
	win.document.write("</td>");
	win.document.write("<td align='right'>");
	win.document.write("<b>Managing Director &nbsp;</b>");
	win.document.write("</td>");
	win.document.write("</tr>");
	win.document.write("</TABLE>");
	win.document.write("</td>");   
	win.document.write("</tr>");
	win.document.write("</TABLE>");
	win.document.write("</td>");   
	win.document.write("</tr>");   
	win.document.write("</TABLE>");
}
function doClose()
{
	window.close();
}
</script>
</head>
<body >
<form name= "orgfrm" method="post" class="normal">
<%if(arrsize>0 || arrSolsize>0 ||arrKpowersize>0){%>
<table class="outertable"  width="100%" border="0" cellspacing="0" cellpadding="3">
        <tr>
          <td align="center"><img src="<%=ApplicationParams.getAppUrl()%>img/kbl_newlogo.jpg"></td>          		
        </tr>
         <tr> 
          <td align="center"><%=Helper.correctNull((String)hshValues.get("Org_Name"))%></td>
        </tr> 
        <tr> 
          <td align="center"><b>Limit Sanction Resolution Register for the period of <%=Helper.correctNull((String)hshValues.get("strFromDate"))%> - <%=Helper.correctNull((String)hshValues.get("strToDate"))%></b></td>
        </tr>
        <tr>
        <td>
          <table width="100%" border="1px" cellspacing="0" cellpadding="3"  class="outertable">
          <tr>
          <td align="center" rowspan="2"><b>Sno</b></td>
          <td align="center" rowspan="2"><b>Branch</b></td>
          <td align="center" rowspan="2"><b>Sanction Reference Number & Date</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Name and Address of Borrower/Co-obligant/Guarantor</b></td>
          <td align="center" nowrap="nowrap" rowspan="1"><b>Nature of Business </b></td>
          <td align="center" nowrap="nowrap" rowspan="1"><b>Constitution </b></td>
           <td align="center" width="200px" rowspan="2" nowrap="nowrap" ><b>Purpose of Advance</b></td>
          <td align="center" width="90px" rowspan="2"><b>Networth</b></td>
          <td align="center" nowrap="nowrap" rowspan="2" width="90px"><b>NWC <br>(in lakhs)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Project Cost <br> in Case of TL</b></td>
          <td align="center" nowrap="nowrap" width="250px" rowspan="1" colspan="5"><b>Prime & Collateral  Security</b></td>
            <td align="center" nowrap="nowrap" rowspan="2"><b> Security Coverage <br>(%)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Nature of Facility & Bank Schematic Code - Amount</b></td>
          <td align="center" width="200px" rowspan="2"><b>Applicable Rate of Interest / Commission</b></td>
           <td align="center" width="200px" rowspan="2"><b>Sanctioned Rate of Interest / Commission</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Periods <br> (months)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Repayment Mode</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Total Liability<br> of Borrower</b></td>
          </tr>
          <tr>
          <td align="center">&nbsp;Sector</td>
          <td align="center">&nbsp;Rating</td>
          <td align="center">&nbsp;Type</td>
          <td align="center">&nbsp;Nature</td>
          <td align="center">&nbsp;Security Amount</td>
          <td align="center">&nbsp;Margin <br>(%)</td>
           <td align="center">&nbsp;Date of Valuation</td>
          </tr>
          <%ArrayList arrvalRow=new ArrayList();
          ArrayList arrvalCol=new ArrayList();
         ArrayList arrvalNew=new ArrayList();
         int arrsizeval=0;
         int j=0,i=0;
         if(arrsize>0){
          for(i=0;i<arrsize;i++)
      		{
        	  ArrCol = (ArrayList) ArrRow.get(i);
      		%>
      		<tr>
      		<td  rowspan="2"><%=i+1 %></td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(13))%></td>
      		<td  rowspan="2"><br><%=Helper.correctNull((String)ArrCol.get(0))%></td>
      		<td  rowspan="2"><table class="outertable">
      		<%String strname="";
      		String strAppName=(String)ArrCol.get(1); 
      		String[] strNameArr=strAppName.split("~");
      		int strArrlen=strNameArr.length;
      		for(int k=0;k<strArrlen;k++)
      		{
      			strname=strNameArr[k];
      			String[] strAppDetails=strname.split("@");
      			String strType=strAppDetails[1];
      			if(strType.equalsIgnoreCase("a")){
          			strType="Applicant";
          		}else if(strType.equals("c")){
          			strType="Joint Applicant";
          		}else if(strType.equals("g")){
          			strType="Co-Obligant / Guarantor";
          		}
          		else if(strType.equals("CO")){
          			strType="Co-Obligant";
          		}
          		else if(strType.equals("G")){
          			strType="Guarantor";
          		}
          		else if(strType.equals("C")){
          			strType="Co-Applicant";
          		}
          		else{
          			strType="";
          		}
      			%>
      			<%if(!strType.equalsIgnoreCase("")) {%>
      			<tr><td><u><b><%=strType%>&nbsp;-&nbsp;<%=strAppDetails[0]%></b></u></td></tr>
      			<tr><td><%=strAppDetails[2]%></td></tr>
      			<%}else{ %>
      			<tr><td><b><%=strAppDetails[2]%>&nbsp;-&nbsp;<%=strAppDetails[0]%></b></td></tr>
      			<%} %>
      			<%if(strType.equalsIgnoreCase("Applicant")){ %>
      			<tr><td><%=strAppDetails[3]%></td></tr>
      			<%} %>
      		<%}
      		%></table></td>
      		<td  rowspan="1"><%=Helper.correctNull((String)ArrCol.get(3))%></td>
      		<td  rowspan="1"><%=Helper.correctNull((String)ArrCol.get(15))%></td>
      		<td  rowspan="2"><table class="outertable"><%String strTemp="";
      		String strPurpose=(String)ArrCol.get(4);
      		arrvalRow=new ArrayList();
      		StringTokenizer st = new StringTokenizer(strPurpose,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td align="right"  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(2))%></td>
      		<td  rowspan="2" align="right" ><%=Helper.correctNull((String)ArrCol.get(20))%>&nbsp;</td>
      		<td align="right"  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(19)) %></td>
      		<td  rowspan="2"><table class="outertable"><%strTemp="";
      		String strSecName=(String)ArrCol.get(21);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table>
			</td>
      		<td  rowspan="2"><table class="outertable"><%strTemp="";
      		strSecName=(String)ArrCol.get(6);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table>
      		</td>
      		<td  rowspan="2"><table class="outertable"><%strTemp="";
      		strSecName=(String)ArrCol.get(22);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td  rowspan="2"><table class="outertable"><%
      		arrvalRow=new ArrayList();
            arrvalCol=new ArrayList();
      		String secval="";
      		String strSecVal=(String)ArrCol.get(7);
      		StringTokenizer st1 = new StringTokenizer(strSecVal,"~");
			while (st1.hasMoreTokens())
			{
				arrvalRow.add(st1.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				secval = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td nowrap='nowrap'>
        	  <%=secval %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td  rowspan="2"><table class="outertable"><%strTemp="";
      		strSecName=(String)ArrCol.get(23);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(18))%>&nbsp;</td>
      		<td nowrap='nowrap'  rowspan="2"><table class="outertable"><%strTemp="";
      		strPurpose=(String)ArrCol.get(5);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strPurpose,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td nowrap>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td nowrap='nowrap'  rowspan="2"><table class="outertable"><%strTemp="";
      		strSecName=(String)ArrCol.get(8);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td  rowspan="2"><table class="outertable"><%strTemp="";
      		strSecName=(String)ArrCol.get(14);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td nowrap='nowrap'  rowspan="2"><table class="outertable"><%strTemp="";
      		strSecName=(String)ArrCol.get(10);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td  rowspan="2"><table class="outertable"><%strTemp="";
      		strSecName=(String)ArrCol.get(9);
      		arrvalRow=new ArrayList();
      		st = new StringTokenizer(strSecName,"~");
			while (st.hasMoreTokens())
			{
				arrvalRow.add(st.nextToken());
			}
			arrsizeval=arrvalRow.size();
			for(j=0;j<arrsizeval;j++)
      		{
				strTemp = (String) arrvalRow.get(j);%>
        	  <tr>
        	  <td nowrap>
        	  <%=strTemp %>
        	  </td>
        	  </tr>
        	 <%
      		}
      		%>
      		</table></td>
      		<td align="right"  rowspan="2"><%=ArrCol.get(12) %>&nbsp;</td>
      		</tr>
      		<tr>
      		<td>&nbsp;<%=Helper.correctNull((String)ArrCol.get(11))%></td>
      		<td>&nbsp;<%=Helper.correctNull((String)ArrCol.get(17))%></td>
      		</tr>
      		<%}}else{ %>
      		<tr><td colspan="22" align="center">&nbsp; - No Record Found -</td></tr>
      		<%} %>
          </table>
        </td>
      </tr>
      <tr><td><b>Total Applications : <%=i %></b></td></tr>
      <tr><td><b>Total Sanctioned Amount : <%=Helper.correctNull((String)hshValues.get("sanctionamt")) %></b></td></tr>
      
      <tr><td>&nbsp;</td></tr>
       <tr> 
          <td align="center"><b>Solvency Sanctioned Application Report for the period of <%=Helper.correctNull((String)hshValues.get("strFromDate"))%> - <%=Helper.correctNull((String)hshValues.get("strToDate"))%></b></td>
        </tr>
        <tr><td>&nbsp;</td></tr>
      
     <tr>
     <td>
     <table width="100%" border="1px" cellspacing="0" cellpadding="3"  class="outertable">
          <tr>
          <td align="center" rowspan="2"><b>Sno</b></td>
          <td align="center" rowspan="2"><b>Branch</b></td>
          <td align="center" rowspan="2"><b>Sanction Reference Number & Date</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Name and Address of Borrower/Co-obligant/Guarantor</b></td>
          <td align="center" nowrap="nowrap" rowspan="1"><b>Nature of Business </b></td>
          <td align="center" nowrap="nowrap" rowspan="1"><b>Constitution </b></td>
           <td align="center" width="200px" rowspan="2" nowrap="nowrap" ><b>Purpose of Advance</b></td>
          <td align="center" width="90px" rowspan="2"><b>Networth</b></td>
          <td align="center" nowrap="nowrap" rowspan="2" width="90px"><b>NWC <br>(in lakhs)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Project Cost <br> in Case of TL</b></td>
          <td align="center" nowrap="nowrap" width="250px" rowspan="1" colspan="5"><b>Prime & Collateral  Security</b></td>
            <td align="center" nowrap="nowrap" rowspan="2"><b> Security Coverage <br>(%)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Nature of Facility & Bank Schematic Code - Amount</b></td>
          <td align="center" width="200px" rowspan="2"><b>Applicable Rate of Interest / Commission</b></td>
           <td align="center" width="200px" rowspan="2"><b>Sanctioned Rate of Interest / Commission</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Periods <br> (months)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Repayment Mode</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Total Liability<br> of Borrower</b></td>
          </tr>
          <tr>
          <td align="center">&nbsp;Sector</td>
          <td align="center">&nbsp;Rating</td>
          <td align="center">&nbsp;Type</td>
          <td align="center">&nbsp;Nature</td>
          <td align="center">&nbsp;Security Amount</td>
          <td align="center">&nbsp;Margin <br>(%)</td>
           <td align="center">&nbsp;Date of Valuation</td>
          </tr>
     
     <%arrvalCol=new ArrayList();
     i=0;
     if(arrSolsize>0){
          for(i=0;i<arrSolsize;i++)
      		{
        	  ArrCol = (ArrayList) ArrSolRow.get(i);
      		%>
      		<tr>
      		<td  rowspan="2"><%=i+1 %></td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(13))%></td>
      		<td  rowspan="2"><br><%=Helper.correctNull((String)ArrCol.get(0))%></td>
      		<td  rowspan="2"><table class="outertable">
      		<%String strname="";
      		String strAppName=(String)ArrCol.get(1); 
      		String[] strNameArr=strAppName.split("~");
      		int strArrlen=strNameArr.length;
      		for(int k=0;k<strArrlen;k++)
      		{
      			strname=strNameArr[k];
      			String[] strAppDetails=strname.split("@");
      			String strType=strAppDetails[1];
      			if(strType.equalsIgnoreCase("a")){
          			strType="Applicant";
          		}
          		else{
          			strType="";
          		}
      			%>
      			<%if(!strType.equalsIgnoreCase("")) {%>
      			<tr><td><u><b><%=strType%>&nbsp;-&nbsp;<%=strAppDetails[0]%></b></u></td></tr>
      			<tr><td><%=strAppDetails[2]%></td></tr>
      			<%}else{ %>
      			<tr><td><b><%=strAppDetails[2]%>&nbsp;-&nbsp;<%=strAppDetails[0]%></b></td></tr>
      			<%} %>
      			<%if(strType.equalsIgnoreCase("Applicant")){ %>
      			<tr><td><%=strAppDetails[3]%></td></tr>
      			<%} %>
      		<%}
      		%></table></td>
      		<td  rowspan="1"><%=Helper.correctNull((String)ArrCol.get(3))%>&nbsp;</td>
      		<td  rowspan="1"><%=Helper.correctNull((String)ArrCol.get(15))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(4))%>&nbsp;</td>
      		<td align="right"  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(2))%>&nbsp;</td>
      		<td  rowspan="2" align="right" ><%=Helper.correctNull((String)ArrCol.get(20))%>&nbsp;</td>
      		<td align="right"  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(19)) %>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(21))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(6))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(22))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(7))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(23))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(18))%>&nbsp;</td>
      		<td nowrap='nowrap'  rowspan="2" align="right"><%=Helper.correctNull((String)ArrCol.get(5))%>&nbsp;</td>
      		<td nowrap='nowrap'  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(8))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(14))%>&nbsp;</td>
      		<td nowrap='nowrap'  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(10))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(9))%>&nbsp;</td>
      		<td align="right"  rowspan="2"><%=ArrCol.get(12) %>&nbsp;</td>
      		</tr>
      		<tr>
      		<td>&nbsp;<%=Helper.correctNull((String)ArrCol.get(11))%></td>
      		<td>&nbsp;<%=Helper.correctNull((String)ArrCol.get(17))%></td>
      		</tr>
      		<%}}else{ %>
      		<tr><td colspan="22"  align="center">&nbsp; - No Record Found -</td></tr>
      		<%} %>
      		
      		
      		</table>
      		</td>
      		</tr>
      		
      		<tr><td><b>Total Applications : <%=i %></b></td></tr>
      <tr><td><b>Total Sanctioned Amount : <%=Helper.correctNull((String)hshValues.get("dblsolsanctamt")) %></b></td></tr>
      
      
      
      <tr><td>&nbsp;</td></tr>
       <tr> 
          <td align="center"><b>K-Power Sanctioned Application Report for the period of <%=Helper.correctNull((String)hshValues.get("strFromDate"))%> - <%=Helper.correctNull((String)hshValues.get("strToDate"))%></b></td>
        </tr>
        <tr><td>&nbsp;</td></tr>
      
     <tr>
     <td>
     <table width="100%" border="1px" cellspacing="0" cellpadding="3"  class="outertable">
          <tr>
          <td align="center" rowspan="2"><b>Sno</b></td>
          <td align="center" rowspan="2"><b>Branch</b></td>
          <td align="center" rowspan="2"><b>Sanction Reference Number & Date</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Name and Address of Borrower/Co-obligant/Guarantor</b></td>
          <td align="center" nowrap="nowrap" rowspan="1"><b>Nature of Business </b></td>
          <td align="center" nowrap="nowrap" rowspan="1"><b>Constitution </b></td>
           <td align="center" width="200px" rowspan="2" nowrap="nowrap" ><b>Purpose of Advance</b></td>
          <td align="center" width="90px" rowspan="2"><b>Networth</b></td>
          <td align="center" nowrap="nowrap" rowspan="2" width="90px"><b>NWC <br>(in lakhs)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Project Cost <br> in Case of TL</b></td>
          <td align="center" nowrap="nowrap" width="250px" rowspan="1" colspan="5"><b>Prime & Collateral  Security</b></td>
            <td align="center" nowrap="nowrap" rowspan="2"><b> Security Coverage <br>(%)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Nature of Facility & Bank Schematic Code - Amount</b></td>
          <td align="center" width="200px" rowspan="2"><b>Applicable Rate of Interest / Commission</b></td>
           <td align="center" width="200px" rowspan="2"><b>Sanctioned Rate of Interest / Commission</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Periods <br> (months)</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Repayment Mode</b></td>
          <td align="center" nowrap="nowrap" rowspan="2"><b>Total Liability<br> of Borrower</b></td>
          </tr>
          <tr>
          <td align="center">&nbsp;Sector</td>
          <td align="center">&nbsp;Rating</td>
          <td align="center">&nbsp;Type</td>
          <td align="center">&nbsp;Nature</td>
          <td align="center">&nbsp;Security Amount</td>
          <td align="center">&nbsp;Margin <br>(%)</td>
          <td align="center">&nbsp;Date of Valuation</td>
          </tr>
     
     <%arrvalCol=new ArrayList();
     i=0;
     if(arrKpowersize>0)
     {
          for(i=0;i<arrKpowersize;i++)
      		{
        	  ArrCol = (ArrayList) ArrKpowRow.get(i);
      		%>
      		<tr>
      		<td  rowspan="2"><%=i+1 %></td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(13))%></td>
      		<td  rowspan="2"><br><%=Helper.correctNull((String)ArrCol.get(0))%></td>
      		<td  rowspan="2"><table class="outertable">
      		<%String strname="";
      		String strAppName=(String)ArrCol.get(1); 
      		String[] strNameArr=strAppName.split("~");
      		int strArrlen=strNameArr.length;
      		for(int k=0;k<strArrlen;k++)
      		{
      			strname=strNameArr[k];
      			String[] strAppDetails=strname.split("@");
      			String strType=strAppDetails[1];
      			if(strType.equalsIgnoreCase("a")){
          			strType="Applicant";
          		}
          		else{
          			strType="";
          		}
      			%>
      			<%if(!strType.equalsIgnoreCase("")) {%>
      			<tr><td><u><b><%=strType%>&nbsp;-&nbsp;<%=strAppDetails[0]%></b></u></td></tr>
      			<tr><td><%=strAppDetails[2]%></td></tr>
      			<%}else{ %>
      			<tr><td><b><%=strAppDetails[2]%>&nbsp;-&nbsp;<%=strAppDetails[0]%></b></td></tr>
      			<%} %>
      			<%if(strType.equalsIgnoreCase("Applicant")){ %>
      			<tr><td><%=strAppDetails[3]%></td></tr>
      			<%} %>
      		<%}
      		%></table></td>
      		<td  rowspan="1"><%=Helper.correctNull((String)ArrCol.get(3))%>&nbsp;</td>
      		<td  rowspan="1"><%=Helper.correctNull((String)ArrCol.get(15))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(4))%>&nbsp;</td>
      		<td align="right"  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(2))%>&nbsp;</td>
      		<td  rowspan="2" align="right" ><%=Helper.correctNull((String)ArrCol.get(20))%>&nbsp;</td>
      		<td align="right"  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(19)) %>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(21))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(6))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(22))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(7))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(23))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(18))%>&nbsp;</td>
      		<td nowrap='nowrap'  rowspan="2" align="right"><%=Helper.correctNull((String)ArrCol.get(5))%>&nbsp;</td>
      		<td nowrap='nowrap'  rowspan="2"><%//=Helper.correctNull((String)ArrCol.get(8))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(14))%>&nbsp;</td>
      		<td nowrap='nowrap'  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(10))%>&nbsp;</td>
      		<td  rowspan="2"><%=Helper.correctNull((String)ArrCol.get(9))%>&nbsp;</td>
      		<td align="right"  rowspan="2"><%=ArrCol.get(12) %>&nbsp;</td>
      		</tr>
      		<tr>
      		<td>&nbsp;<%=Helper.correctNull((String)ArrCol.get(11))%></td>
      		<td>&nbsp;<%=Helper.correctNull((String)ArrCol.get(17))%></td>
      		</tr>
      		<%}}else{ %>
      		<tr><td colspan="22"  align="center">&nbsp; - No Record Found -</td></tr>
      		<%} %>
      		
      		</table>
      		</td>
      		</tr>
      		
      		<tr><td><b>Total Applications : <%=i %></b></td></tr>
      <tr><td><b>Total Sanctioned Amount : <%=Helper.correctNull((String)hshValues.get("dblkpowersanctamt")) %></b></td></tr>
      		
      		</table>

<br>
<lapschoice:combuttonnew btnnames="Print Preview" btnenable='<%=Helper.correctNull((String)request.getParameter("btnenable"))%>' />
 <%}else{ %>
 <table class="outertable"  width="95%" border="0" cellspacing="0" cellpadding="3" align="center">
        <tr>
          <td align="center"><img src="<%=ApplicationParams.getAppUrl()%>img/kbl_newlogo.jpg"></td>          		
        </tr>
         <tr> 
          <td align="center"><%=Helper.correctNull((String)hshValues.get("Org_Name"))%></td>
        </tr> 
        <tr> 
          <td align="center"><b>Limit Sanction Resolution Register for the period of <%=Helper.correctNull((String)hshValues.get("strFromDate"))%> - <%=Helper.correctNull((String)hshValues.get("strToDate"))%></b></td>
        </tr>
        <tr><td>&nbsp;</td></tr>
       <tr class="font_style datagrid" >
				<td align="center">No Record Found</td>
			</tr>
          <%} %>
</form>
</body>
</html>