<%@ page import="com.sai.laps.helper.*"%>
<%@ page import="com.sai.laps.helper.*,java.util.*"%>
<%@ taglib prefix="lapschoice" uri="/WEB-INF/laps.tld"%>
<jsp:useBean id="hshValues" class="java.util.HashMap" scope="request" />
<lapschoice:handleerror />
<%
  ArrayList arrRow=new ArrayList();
  ArrayList arrCol=new ArrayList();
  if(hshValues!=null){
  arrRow=(ArrayList)hshValues.get("arrRow");
  }
  int intsize=0,intsize1=0;
  String strtota1="",strtotal2="",strtotal3="",strtotal4="",strtotal5="",strtotal6="",strtotal7="";
  if(arrRow!=null && arrRow.size()>0)
  {
	  intsize=arrRow.size();
	  intsize1=intsize;
  }
  
%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet"	href="<%=ApplicationParams.getAppUrl()%>css/style.css"	type="text/css">
<script>

var datalen ="<%=intsize%>";

		
function doClose()
{
	window.close();
}
function doPrintPreview()
{

	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=1000,height=500,left=60,top=40");
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("<link rel='stylesheet'	href='<%=ApplicationParams.getAppUrl()%>css/report.css'	type='text/css'>");
	win.document.write("</head>");
	win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");
	win.document.write("<table width='100%' border='0' cellspacing='0' cellpadding='3'>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><img src='"+<%=ApplicationParams.getAppUrl()%>+"img/kbl_newlogo.jpg'></td>");           		
	win.document.write("</tr>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><strong>Karnataka Bank Ltd.</strong></td>");
	win.document.write("</tr>");
	win.document.write("</table>");
	
	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><B><center>Credit Sales Report Generation</center></B></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");

	win.document.write("<TABLE border='0' width='100%'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated By :<%=Helper.correctNull((String)hshValues.get("genby"))%></B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+''+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated On :<%=Helper.getCurrentDateTime()%></B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+''+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");
	if(datalen >=0){
    win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='0' bordercolor='#eeeeee' >");
				win.document.write("<tr>");
				win.document.write("<td height='30'> ");
				win.document.write("<div align='center' nowrap><B>S.No</B></div>");
				win.document.write("</td>");
				win.document.write("<td height='30'> ");
				win.document.write("<div align='center' nowrap><B>Disbursed Branch Code</B></div>");
				win.document.write("</td>");
				win.document.write("<td height='30'> ");
				win.document.write("<div align='center' nowrap><B>Disbursed Branch Name</B></div>");
				win.document.write("</td>");
				win.document.write("<td height='30'> ");
				win.document.write("<div align='center' nowrap><B>Regional Office Name</B></div>");
				win.document.write("</td>");
				win.document.write("<td height='30'> ");
				win.document.write("<div align='center' nowrap><B>Customer ID</B></div>");
				win.document.write("</td>");
				win.document.write("<td height='30'> ");
				win.document.write("<div align='center' nowrap><B>Customer Name</B></div>");
				win.document.write("</td>");
				win.document.write("<td height='30'> ");
				win.document.write("<div align='center' nowrap><B>Sanctioned Amount</B></div>");
				win.document.write("</td>");
				win.document.write("<td height='30'> ");
				win.document.write("<div align='center' nowrap><B>Sanctioned On</B></div>");
				win.document.write("</td>");
				win.document.write("<td  height='30'> ");
				win.document.write("<div align='center' nowrap><B>Scheme Name</B></div>");
				win.document.write("</td>");
				win.document.write("<td  height='30'> ");
				win.document.write("<div align='center' nowrap><B>LAR Number</B></div>");
				win.document.write("</td>");
				win.document.write("<td  height='30'> ");
				win.document.write("<div align='center' nowrap><B>Sanction Reference Number</B></div>");
				win.document.write("</td>");
				win.document.write("<td  height='30'> ");
				win.document.write("<div align='center' nowrap><B>Digi Application Number</B></div>");
				win.document.write("</td>");
				win.document.write("<td  height='30'> ");
				win.document.write("<div align='center' nowrap><B>Eligible Under DIGI</B></div>");
				win.document.write("</td>");
				win.document.write("<td  height='30'> ");
				win.document.write("<div align='center' nowrap><B>Reasons</B></div>");
				win.document.write("</td>");
				win.document.write("<td  height='30'> ");
				win.document.write("<div align='center' nowrap><B>Brief Description</B></div>");
				win.document.write("</td>");
				win.document.write("<td  height='30'> ");
				win.document.write("<div align='center' nowrap><B>Comments</B></div>");
				win.document.write("</td>");
				win.document.write("</tr>");
				

				<% if (arrRow!=null && arrRow.size() > 0)
				{
					for(int i=0;i<arrRow.size();i++)
					 { 
						  arrCol = new ArrayList();
					 	  arrCol =(ArrayList)arrRow.get(i);
					 	%>
				   	win.document.write("<TR align='center'>");	
				   	win.document.write("<TD>");
				   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(0)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD>");
				   	win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(1)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(2)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(3)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(4)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(5)%>"+'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(6)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(7)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(8)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(9)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(10)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(11)%>"+'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(12)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(14)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				  	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(13)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("<TD align='left'>");
				   	win.document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(13)%>" +'&nbsp;'+ "</font></div>");
				   	win.document.write("</TD >");
				   	win.document.write("</TR>");	
		<%}}%>
         	
}
else
{
		 win.document.write("<center><TABLE border='1' width='100%' cellspacing='0' cellpadding='0' bordercolor='#eeeeee' >");
		 win.document.write("<tr><td align='center'>No Data Found</td></tr>");
}
win.document.write("</table>");
win.document.write("</center>"); 
win.document.write("<table>");
win.document.write("<tr>");
win.document.write("<td><B>Total Applications = "+'<%=intsize1%>');
win.document.write("</B></td>");
win.document.write("</tr>");
win.document.write("</table>");
win.document.write("</body>");
win.document.write("</html>");
}


function doPrintPreview2()
{
if(datalen >=0){

	document.write("<tr>");
	document.write("<td  height='30'> ");
	document.write("<div align='center'><B> S.No </B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Disbursed Branch Code</B></div>");
	document.write("</td>");
	document.write("<td  height='30'> ");
	document.write("<div align='center' nowrap><B>Disbursed Branch Name</B></div>");
	document.write("</td>");
	document.write("<td  height='30'> ");
	document.write("<div align='center' nowrap><B>Regional Office Name</B></div>");
	document.write("</td>");
	document.write("<td  height='30'> ");
	document.write("<div align='center' nowrap><B>Customer ID</B></div>");
	document.write("</td>");
	document.write("<td  height='30' > ");
	document.write("<div align='center' nowrap><B>Customer Name</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Sanctioned Amount</B></div>");
	document.write("</td>");
	document.write("<td  height='30'> ");
	document.write("<div align='center' nowrap><B>Sanctioned On</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Scheme Name</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>LAR Number</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Sanction Reference Number</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Digi Application Number</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Eligible Under DIGI</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Reasons</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Brief Description</B></div>");
	document.write("</td>");
	document.write("<td   height='30'> ");
	document.write("<div align='center' nowrap><B>Comments</B></div>");
	document.write("</td>");
	document.write("</tr>");

	<% if (arrRow!=null && arrRow.size() > 0)
	{
		for(int i=0;i<arrRow.size();i++)
		 { 
			  arrCol = new ArrayList();
		 	  arrCol =(ArrayList)arrRow.get(i);
		 	%>
	   document.write("<TR align='center'>");	
	   	document.write("<TD>");
	   	 document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(0)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD>");
	   	 document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(1)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(2)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(3)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(4)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(5)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left' nowrap>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(6)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(7)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left' nowrap>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(8)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(9)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(10)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(11)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(12)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left' nowrap>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(14)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(13)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("<TD align='left'>");
	   	 document.write("<div><font size='1' face='MS Sans Serif'>"+"<%=arrCol.get(16)%>" +'&nbsp;'+ "</font></div>");
	   	 document.write("</TD >");
	   	 document.write("</TR>");	
	   	<%	} } %>
         		
}
else
{
	 document.write("<tr><td align='center'>No Data Found</td></tr>");
}

document.write("<table>");
document.write("<tr>");
document.write("<td><B>Total Applications = "+'<%=intsize%>');
document.write("</B></td>");
document.write("</tr>");
document.write("</table>");
}



</script>
</head>
<body>
<br>
<form name= "orgfrm" method="post" class="normal">
<table width="100%" border="0" cellspacing="0" cellpadding="3" class="outertable">
        <tr>
          <td align="center"><img src="<%=ApplicationParams.getAppUrl()%>img/kbl_newlogo.jpg"></td>          		
        </tr>
        <tr> 
          <td align="center"><strong>Karnataka Bank Ltd.</strong></td>
        </tr>
       <tr> 
          <td align="center"><b>Credit Sales Report Generation </b></td>
        </tr>
       <tr>
        <td align="center"><b>Generated By :<%=Helper.correctNull((String)hshValues.get("genby"))%> </b></td>
        </tr>
        <tr>
        <td align="center"><b>Generated On :  <%=Helper.getCurrentDateTime()%></b></td>
        </tr> 
                 
    </table>
    
    
    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="outertable" align="center">
      <tr> 
        <td > 
          <table width="100%" border="1" cellspacing="0" cellpadding="0"  class="outertable">
            <script>
        
            doPrintPreview2();
			
 		</script>
          </table>
        </td>
      </tr>
    </table>
<br>

 	<lapschoice:combuttonnew btnnames="Print Preview" btnenable='<%=Helper.correctNull((String)request.getParameter("btnenable"))%>' />  
 
<input type="hidden" name ="hiduserOrgCode" value ="">
</form>
</body>
</html>
