<%@ include file="../share/directives.jsp"%>
<%@ taglib prefix ="laps"  uri="/WEB-INF/laps.tld" %>

<%
  ArrayList vecOrg = new ArrayList();
  vecOrg=(ArrayList)hshValues.get("vecValues");
  String align="left";
  	
%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet"	href="<%=ApplicationParams.getAppUrl()%>css/style.css"	type="text/css">
<script>
var outlabel="<%= hshValues.get("labels")%>";
var textlabel="";
var per="<%= hshValues.get("txtDate")%>";
var datalen ="<%= vecOrg.size()%>";
function doClose()
{
	window.close();
}
function doPrintPreview()
{
	if (datalen > 0)
   	{
	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=600,height=450,left=60,top=40");
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("<link rel='stylesheet'	href='<%=ApplicationParams.getAppUrl()%>css/report.css'	type='text/css'>");
	win.document.write("</head>");
	win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");

	win.document.write("<table width='100%' border='0' cellspacing='0' cellpadding='3'>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><img src='"+'<%=ApplicationParams.getAppUrl()%>'+"img/kbl_newlogo.jpg'></td>");          		
	win.document.write("</tr>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><b>"+'<%=Helper.correctNull((String)hshValues.get("OrgName"))%>'+"</b></td>");
	win.document.write("</tr>");
	win.document.write("</table>");
	
	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><B><center>Disposal of applications Summary </center></B></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");

	win.document.write("<TABLE border='0' width='100%'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated By :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("genby")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated On :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("txtSaveDate")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Period :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("txtDate")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD></TD>");
	win.document.write("<TD></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");

    win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='0' bordercolor='#eeeeee' >");
		var agln="";
			
		 textlabel =outlabel.split(',');
		 for(l=0;l<textlabel.length;l++)
			{
				win.document.write("<td width='11%' height='30'> ");
				win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ textlabel[l] + "</B></font></div>");
				win.document.write("</td>");
			}
				win.document.write("<tr>"); 
				win.document.write("</tr>"); 
			
			
			<%if (vecOrg.size() > 0)
			{
				String strtemp="";
				for(int i1=0;i1<vecOrg.size();i1++)
				{
				  ArrayList vecVal = new ArrayList();
				  vecVal =(ArrayList)vecOrg.get(i1);
			 %>
				  
				  win.document.write("</tr>");
			<%	  for(int j1=0;j1<vecVal.size();j1++)
				  { 
				if(j1==0)
		   		{
		   			String stp = (String)vecVal.get(j1);		
		   			align =(String)vecVal.get(j1+1);
					if (!(stp.trim().equals("")) && !(strtemp.trim().equals(stp)))
					{
						strtemp =stp;
		   		%>			   			
		   			win.document.write("<td height = '30' colspan='4' align='<%=align%>'>");
		   			win.document.write("<div align='<%=align%>'>&nbsp;<font size='1' face='MS Sans Serif'><b>"+"<%=stp%>" + "&nbsp;</b></font></div>");
					win.document.write("</td></tr>");
		   			win.document.write("<tr>");
		   			
		   		<%}
		   		}
		   		else
		   		{
				
					String stp = (String)vecVal.get(j1);
					align =(String)vecVal.get(j1+1);
					if (stp.equals(" "))
					{
						stp="&nbsp;";
					}
             %>
					win.document.write("<td width='20%'align='<%=align%>'>&nbsp;<font size='1' face='MS Sans Serif'>"+"<%=stp%>"+'&nbsp;'+"</td> ");	
			<%	
				  }
			j1=j1+1; 
				}
			%>
				  win.document.write("</tr>");
			<%	}
			}
			%>
		win.document.write("</TABLE></center>");
		win.document.write("</body>");
		win.document.write("</html>");
	}
}

function printData()
{
	if (datalen > 0)
   	{
	textlabel =outlabel.split(',');
		 for(l=0;l<textlabel.length;l++)
			{
				document.write("<td width='11%' height='30'> ");
				document.write("<div align='center'><B>"+ textlabel[l] + "</B></div>");
				document.write("</td>");
			}
	}
   else
	{
	   document.write("<tr><td align='center'>No Data Found</td></tr>");
	}	
         <%
         String strtemp="";
		  for(int i=0;i<vecOrg.size();i++)
		  {
			  ArrayList ht = new ArrayList();
			  ht =(ArrayList)vecOrg.get(i);
			 
		  %>
				document.write("<tr>");
		   <%	for(int j=0;j<ht.size();j++)
			    {
			   		if(j==0)
			   		{
			   			String dt = (String)ht.get(j);		
			   			align =(String)ht.get(j+1);
						if (!(dt.trim().equals("")) && !(strtemp.trim().equals(dt)))
						{
							strtemp =dt;
			   		%>			   			
			   			document.write("<td height = '30' colspan='4' align='<%=align%>'>");
			   			document.write("<div align='<%=align%>'>&nbsp;<b>"+"<%=dt%>" + "&nbsp;</b></div>");
						document.write("</td></tr>");
			   			document.write("<tr>");
			   			
			   		<%}
			   		}
			   		else
			   		{
						String dt = (String)ht.get(j);
						align =(String)ht.get(j+1);
						if (dt.trim().equals(""))
						{
							dt="&nbsp;";
						}		
			%>			document.write("<td height = '30' align='<%=align%>'>");
						document.write("<div align='<%=align%>'>&nbsp;"+"<%=dt%>" + "&nbsp;</div>");
						document.write("</td>");
					
			<%	   }
			   	j= j+1;
				   
			   }%>
				document.write("</tr>");					
		  <%}
		%>
}


</script>
</head>

<body>
<br>
<form name= "orgfrm" method="post" class="normal">
<table width="100%" border="0" cellspacing="0" cellpadding="3" class="outertable">
        <tr>
          <td align="center"><img src="<%=ApplicationParams.getAppUrl()%>img/kbl_newlogo.jpg"></td>          		
        </tr>
         <tr> 
          <td align="center"><%=Helper.correctNull((String)hshValues.get("OrgName"))%></td>
        </tr> 
        <tr> 
          <td align="center"><b>Disposal of applications Summary</b></td>
        </tr>
   </table>
<div class="cellContainer">
  
    <table width="100%" border="1" cellspacing="0" cellpadding="0" class="outertable" align="center">
      <table width="100%" border="0" cellspacing="0" cellpadding="3" class="outertable">
	   	
	</table>
      <tr> 
        <td > 
          <table width="100%" border="1" cellspacing="0" cellpadding="0"  class="outertable">
            <script>
         
			printData();
 		</script>
          </table>
        </td>
      </tr>
    </table>
  </div>
<br>
<lapschoice:combuttonnew btnnames="Print Preview"
							btnenable='<%=Helper.correctNull((String)request.getParameter("btnenable"))%>' />
</form>
</body>
</html>
