<%@ page import="com.sai.laps.helper.*,java.util.*"%>
<%@ taglib prefix="laps" uri="/WEB-INF/laps.tld"%>
<jsp:useBean id="hshValues" class="java.util.HashMap" scope="request" />
<laps:handleerror />

<%//out.println("****************"+hshValues);
			ArrayList vecOrg = new ArrayList();
			vecOrg = (ArrayList) hshValues.get("vecValues");
			java.text.NumberFormat nf = java.text.NumberFormat
					.getNumberInstance();
			nf.setGroupingUsed(true);
			nf.setMaximumFractionDigits(2);
			nf.setMinimumFractionDigits(2);
			String align = "left";
			ArrayList vecVal = null;

			%>


<html>
<head>
<title>Report - Productwise Status Report</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" href="<%=ApplicationParams.getAppUrl()%>css/report.css" type="text/css">
<script>
var outlabel="<%= hshValues.get("labels")%>";
var textlabel="";
var datalen ="<%= vecOrg.size()%>";
</script>

</head>
<body bgcolor="#FFFFFF" text="#000000" leftmargin="0" topmargin="0"
	marginwidth="0" marginheight="0">
<table width="100%" border="0" cellspacing="0" cellpadding="3">
	<tr>
		<td align="center"><img
			src="<%=ApplicationParams.getAppUrl()%>img/kbl_newlogo.jpg"></td>
	</tr>
	<tr>
		<td align="center"><%=Helper.correctNull((String) hshValues.get("OrgName"))%></td>
	</tr>
	<tr>
		<td align="center"><b>Productwise Status Report for</b></td>
	</tr>
	<tr>
		<td align="center"><b><%=Helper.correctNull((String) hshValues.get("prd"))%></b></td>
	</tr>
</table>


<%if (vecOrg.size() > 0) {

				%>
<br>
<table width="100%" border="0" cellspacing="0" cellpadding="2">
	<tr>
		<td width="12%"><font size="1" face="MS Sans Serif"><b>Organisation</b></font></td>
		<td width="38%"><font size="1" face="MS Sans Serif"><%=(String) hshValues.get("OrgName")%></font></td>
		<td width="16%"><b><font size="1" face="MS Sans Serif">Generated By</font></b></td>
		<td width="34%"><font size="1" face="MS Sans Serif"><%=(String) hshValues.get("genby")%></font></td>
	</tr>
	<tr>
		<td width="12%"><font size="1" face="MS Sans Serif"><b>Period</b></font></td>
		<td width="38%"><font size="1" face="MS Sans Serif"><%=(String) hshValues.get("txtDate")%></font></td>
		<td width="16%"><b><font size="1" face="MS Sans Serif">Generated On</font></b></td>
		<td width="34%"><font size="1" face="MS Sans Serif"><%=(String) hshValues.get("txtSaveDate")%></font></td>
	</tr>
	<tr>
		<td width="12%">&nbsp;</td>
		<td width="38%"><font size="1" face="MS Sans Serif"></font></td>
		<td width="16%">&nbsp;</td>
		<td width="34%">&nbsp;</td>
	</tr>
</table>
<br>

	<table width="100%" border="1" cellspacing="1" cellpadding="2"
		bordercolor="#eeeeee">
		<tr>
			<td width="16%"><b>Category</b></td>
			<%if(Helper.correctNull((String)hshValues.get("LoanType")).equalsIgnoreCase("p")){ %>
			<td colspan="3" width="84%"><font size="1" face="MS Sans Serif">Retail</font></td>
			<%}
			else
			{%>
			<td colspan="3" width="84%"><font size="1" face="MS Sans Serif">Agriculture</font></td>
			<%} %>
		</tr>
		<tr>
			<td width="16%"><font size="1" face="MS Sans Serif"><b>Sub Category</b></font></td>
			<td colspan="3" width="84%"><font size="1" face="MS Sans Serif"> <%=Helper.correctNull((String) hshValues.get("prodcat"))%></font></td>
		</tr>
				<tr>
					<td colspan="4">
					<table width="100%" border="1" cellspacing="0" cellpadding="3"
						bordercolor="#eeeeee">
						<tr>
							<td align="right" colspan="6"><b>(Rs.in lacs)</b></td>
						</tr>
						<tr>
							<td width="15%">
							<div align="left"><font color="#000000"><b>Proposal Number</b></font></div>
							</td>
							<td width="20%" align="left"><b>Applicant Name</b></td>
							<td width="17%" align="center"><b>Date Approved</b></td>
							<td width="18%" align="center"><b>Loan Amount Applied</b></td>
							<td width="13%" align="center"><b>Loan Amount Sanctioned</b></td>
							<td width="13%" align="center"><b>Proposal Type</b></td>
							
						</tr>
						<%String subtot = "0.00";
						int prdcode = 0;
						HashMap hshsub = new HashMap();
		
						for (int i = 0; i < vecOrg.size(); i++) {
		
							vecVal = new ArrayList();
							if (vecOrg.get(i) instanceof HashMap) {
								hshsub = (HashMap) vecOrg.get(i);
								subtot = (String) hshsub.get("subtot");
		
							}
							if (vecOrg.get(i) instanceof ArrayList) {
								vecVal = (ArrayList) vecOrg.get(i);
							}
							String proposaltype=Helper.correctNull((String) vecVal
									.get(6));
							
							if (proposaltype.equalsIgnoreCase("S"))
								proposaltype = "Resturcture";
							else if (proposaltype.equalsIgnoreCase("R"))
								proposaltype = "Renew";
							else if (proposaltype.equalsIgnoreCase("P"))
								proposaltype = "Postsanction";
							else
								proposaltype = "Fresh";
							%>
						<tr>
							<td><%=Helper.correctNull((String) vecVal.get(0))%></td>
							<td><%=Helper.correctNull((String) vecVal.get(1))%></td>
							<td align="center"> <%if (Helper.correctNull((String) vecVal.get(2))
									.equalsIgnoreCase("")) {
								out.println("");
							} else {
								out.println(Helper.correctNull((String) vecVal
										.get(2)));
							}
							%> 
							</td>
							<td align="center"><%=nf.format(Double.parseDouble((String) vecVal
									.get(3)))%>
							</td>
							<td align="center"><%=nf.format(Double.parseDouble((String) vecVal
									.get(4)))%>
							</td>
							<td align="center"><%=proposaltype%>
							</td>
						</tr>
			
<%}
				%>
				</table>
<table width="100%">
	<tr>
		<td width="14%" height="20">&nbsp;</td>
		<td width="21%" height="20">&nbsp;</td>
		<td width="20%" height="20">&nbsp;</td>
		<td width="18%" height="20"><b>Grand
		Total : </b></td>
		<td width="18%" height="20"><font size="1" face="MS Sans Serif">&nbsp;&nbsp;<%=nf.format(Double.parseDouble((String) hshValues
								.get("subtot")))%></font></td>
		<td width="12%" height="20">&nbsp;</td>
	</tr>
</table>
<%} else {
%>
<h2>
<center>No Data Found</center>
</h2>
<%}

		%>
<br>
</body>
</html>

