<%@include file="../../share/directives.jsp"%>
<%
  ArrayList vecOrg = new ArrayList();
  vecOrg=(ArrayList)hshValues.get("vecValues");
  String align="left";
  	
%>

<html>
<head>
<title>LAPS</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script>
var outlabel="<%= hshValues.get("labels")%>";
var textlabel="";
var datalen ="<%= vecOrg.size()%>";
var per="<%= hshValues.get("txtDate")%>";
function printpreview()
{
	if (datalen > 0)
   	{
	win = window.open("","","scrollbars=yes,toolbars=Yes,menubar=Yes,width=800,height=450,left=60,top=40");
	win.document.write("<head>");
	win.document.write("<title>LAPS</title>");
	win.document.write("<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>");
	win.document.write("<link rel='stylesheet'	href='<%=ApplicationParams.getAppUrl()%>css/report.css'	type='text/css'>");
	win.document.write("</head>");
	win.document.write("<body bgcolor='#FFFFFF' text='#000000'>");

	win.document.write("<table width='100%' border='0' cellspacing='0' cellpadding='3'>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><img src='"+'<%=ApplicationParams.getAppUrl()%>'+"img/bank_rep_logo.jpg'"+" width='30' height='20'></td>");          		
	win.document.write("</tr>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><strong>Karnataka Bank Ltd.</strong></td>");
	win.document.write("</tr>");
	win.document.write("<tr>");
	win.document.write("<td align='center'><b>"+'<%=Helper.correctNull((String)hshValues.get("Org_Name"))%>'+"</b></td>");
	win.document.write("</tr>");
	win.document.write("</table>");
	
	win.document.write("<center>");
	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><B><center>Turnaround time Report for "+'<%=Helper.correctNull((String)hshValues.get("strStatus"))%>'+" Appliactions</center></B></TD>");
	win.document.write("</TABLE>");
	win.document.write("</center>");

	win.document.write("<TABLE border='0'>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated By :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("genby")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Generated On :</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+'<%=(String)hshValues.get("txtSaveDate")%>'+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD width='20%'><font size='1' face='MS Sans Serif'><B>Period:</B></font></TD>");
	win.document.write("<TD ><font size='1' face='MS Sans Serif'>"+per+"</font></TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("<TR>");
	win.document.write("<TD > </TD>");
	win.document.write("<TD > </TD>");
	win.document.write("</TR>");
	win.document.write("</TABLE>");

    win.document.write("<center><TABLE border='1' cellspacing='0' cellpadding='3' bordercolor='#eeeeee'>");
		var agln="";
			
		 textlabel =outlabel.split(',');
		 	win.document.write("<td > ");
			win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ "Sno" + "</B></font></div>");
			win.document.write("</td>")
		 for(l=0;l<textlabel.length;l++)
			{
				win.document.write("<td > ");
				win.document.write("<div align='center'><font size='1' face='MS Sans Serif'><B>"+ textlabel[l] + "</B></font></div>");
				win.document.write("</td>");
			}
				win.document.write("<tr>"); 
				win.document.write("</tr>"); 
			
			
			<%if (vecOrg.size() > 0)
			{
				for(int i1=0;i1<vecOrg.size();i1++)
				{
				  ArrayList vecVal = new ArrayList();
				  vecVal =(ArrayList)vecOrg.get(i1);
			 %>
				  
				    win.document.write("</tr>");
				    win.document.write("<td align='center'>");
					win.document.write("<div align='center'><font size='1' face='MS Sans Serif'>"+"<%=(i1+1)%>" +'&nbsp;'+ "</font></div>");
					win.document.write("</td>");
			<%	  for(int j1=0;j1<vecVal.size();j1++)
				  { 
					String stp = (String)vecVal.get(j1);
					align =(String)vecVal.get(j1+1);
					if (stp.equals(" "))
					{
						stp="&nbsp;";
					}
             %>
					win.document.write("<td align='<%=align%>'><font size='1' face='MS Sans Serif'>"+"<%=stp%>"+'&nbsp;'+"</td> ");	
			<%	j1=j1+1; 
				}
			%>
				  win.document.write("</tr>");
			<%	}
			}
			%>
		win.document.write("</TABLE></center>");
		win.document.write("</body>");
		win.document.write("</html>");
	}
}

function printData()
{
	if (datalen > 0)
   	{
	textlabel =outlabel.split(',');
	document.write("<td> ");
				document.write("<div align='center'><B>"+ "Sno" + "</B></div>");
				document.write("</td>")
		 for(l=0;l<textlabel.length;l++)
			{
				document.write("<td> ");
				document.write("<div align='center'><B>"+ textlabel[l] + "</B></div>");
				document.write("</td>");
			}
	}
   else
	{
	   document.write("<tr><td align='center'>No Data Found</td></tr>");
	}	
         <%
		  for(int i=0;i<vecOrg.size();i++)
		  {
			  ArrayList ht = new ArrayList();
			  ht =(ArrayList)vecOrg.get(i);
		  %>
				document.write("<tr>");
				document.write("<td align='center'>");
					document.write("<div align='center'>"+"<%=(i+1)%>" +'&nbsp;'+ "</div>");
					document.write("</td>");
		   <%	for(int j=0;j<ht.size();j++)
			    {
					String dt = (String)ht.get(j);
					align =(String)ht.get(j+1);
					if (dt.equals(""))
					{
						dt="&nbsp;";
					}
					
			%>		
					document.write("<td align='<%=align%>'>");
					document.write("<div align='<%=align%>'>"+"<%=dt%>" + "s</div>");
					document.write("</td>");
					
			<%	j= j+1;
				}%>
				document.write("</tr>");					
		  <%}
		%>
}


</script>
<link rel="stylesheet"	href="<%=ApplicationParams.getAppUrl()%>css/style.css"	type="text/css">
</head>

<body>
<form class="normal" name= "orgfrm" method="post">
<table class="outertable" width="100%" border="0" cellspacing="0" cellpadding="3">
        <tr>
          <td align="center"><img src="<%=ApplicationParams.getAppUrl()%>img/bank_rep_logo.jpg"></td>          		
        </tr>
        <tr> 
          <td align="center"><strong>Karnataka Bank Ltd.</strong></td>
        </tr>
         <tr> 
          <td align="center"><%=Helper.correctNull((String)hshValues.get("Org_Name"))%></td>
        </tr> 
        <tr> 
          <td align="center"><b>Turnaround time Report for <%=Helper.correctNull((String)hshValues.get("strStatus"))%> Applications</b></td>
        </tr>
   </table>
<div class="cellContainer">
  
    <table class="outertable border1" width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
      <tr> 
        <td height="3"> 
          <table class="outertable border1" width="100%" border="0" cellspacing="0" cellpadding="3" >
            <script>
         
			printData();
 		</script>
          </table>
        </td>
      </tr>
    </table>
  </div>
<br>
  <table class="outertable border1" border="0" cellspacing="0" cellpadding="0" align="center">
    <tr> 
      <td height="17"> 
        <table class="outertable" width="100%" border="0" cellspacing="0" cellpadding="2">
          <tr> 
            <td width="45%"> 
              <div align="center"> 
                <input type="button" name="Button232253" value="&lt;&lt; Previous" class="buttonclose" onClick="window.close()">
              </div>
            </td>
            <td width="55%"> 
              <div align="center"> 
                <input type="button" name="Button2322532" value="Print Preview" class="buttonothers" onclick="printpreview()">
              </div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
  <br>
</form>
</body>
</html>
