-------------------------------------------------------------------
--DDL for Additional_parameter
-------------------------------------------------------------------
CREATE TABLE ADDITIONAL_PARAMETER 
   (	PARAM_APPNO VARCHAR2(50 BYTE), 
	OCCUPATIONLIST VARCHAR2(50 BYTE), 
	GUARDIAN VARCHAR2(50 BYTE), 
	MINOR VARCHAR2(50 BYTE), 
	PERMANENT_COUNTRY VARCHAR2(50 BYTE), 
	DATE_NONRESIDENT DATE, 
	TRADE_FINANCE VARCHAR2(50 BYTE), 
	TRADE_INLAND VARCHAR2(50 BYTE), 
	INTR_TITLE VARCHAR2(50 BYTE), 
	INTR_NAME VARCHAR2(50 BYTE), 
	CONSTITUTION VARCHAR2(50 BYTE), 
	RELATION_ADDRESS VARCHAR2(4000 BYTE), 
	EMPLOYER_COUNTRY VARCHAR2(50 BYTE), 
	COMTYPE VARCHAR2(50 BYTE)
   );
------------------------------------------------------------
 --DDL for TERMSCOND
------------------------------------------------------------
 CREATE TABLE TERMSCOND 
   (	TERMS_ID NUMBER(10,0), 
	TERMS_DESC VARCHAR2(50 BYTE), 
	TERMS_CONTENT LONG
   );
------------------------------------------------------------
 --DDL for NPAMASTER
------------------------------------------------------------
CREATE TABLE NPAMASTER 
   (	NPA_NO NUMBER(10,0), 
	NPA_LOANNO VARCHAR2(20 BYTE), 
	NPA_DATE DATE, 
	NPA_ACTION_GROUP VARCHAR2(50 BYTE)
   );
------------------------------------------------------------
 --DDL for POST_DISBURSAL
------------------------------------------------------------
CREATE TABLE POST_DISBURSAL 
   (	PD_APPNO VARCHAR2(20 BYTE), 
	PD_BORROWERNUMBER VARCHAR2(50 BYTE), 
	PD_DTOFDISBURSEMENT DATE, 
	PD_TYPEOFACCOUNT VARCHAR2(50 BYTE), 
	PD_ACCOUNTNUMBER VARCHAR2(50 BYTE), 
	PD_BALANCEOUTSTANDING NUMBER(18,2), 
	PD_DTOFEXECDOCUMENT DATE, 
	PD_DTCREATEMORTGAGE DATE, 
	PD_DTRENEWAL DATE, 
	PD_AMTINSURANCE NUMBER(18,2), 
	PD_DTINSURANCE DATE, 
	PD_DTEXPIRYINSURANCE DATE, 
	PD_VEHICLEREGNO VARCHAR2(50 BYTE), 
	PD_DTPRESANCREPORT DATE, 
	PD_DTENTEREDON DATE
   );
------------------------------------------------------------
 --DDL for POST_DISBURSALDETAILS_COM
------------------------------------------------------------

CREATE TABLE POST_DISBURSALDETAILS_COM 
   (	PD_APPNO VARCHAR2(20 BYTE), 
	PD_BORROWERNUMBER VARCHAR2(50 BYTE), 
	PD_DTOFEXECDOCUMENT DATE, 
	PD_DTCREATEMORTGAGE DATE, 
	PD_DTRENEWAL DATE, 
	PD_AMTINSURANCE NUMBER(18,2), 
	PD_DTINSURANCE DATE, 
	PD_DTEXPIRYINSURANCE DATE, 
	PD_DTPRESANCREPORT DATE
   );
------------------------------------------------------------
 --DDL for POSTDISBRULES
------------------------------------------------------------
 CREATE TABLE POSTDISBRULES 
   (	PDB_QID CHAR(4 BYTE), 
	PDB_YESVALUE NUMBER(18,2), 
	PDB_NOVALUE NUMBER(18,2), 
	PDB_NAVALUE NUMBER(18,2), 
	PDB_TYPE CHAR(1 BYTE)
   );
------------------------------------------------------------
 --DDL for POSTDISBSIGNAL
------------------------------------------------------------
CREATE TABLE POSTDISBSIGNAL 
   (	PDS_QID CHAR(4 BYTE), 
	PDS_FROM NUMBER(18,2), 
	PDS_TO NUMBER(18,2), 
	PDS_POINTS NUMBER(18,2), 
	PDS_TYPE CHAR(1 BYTE)
   );
------------------------------------------------------------
 --DDL for COM_POSTDISBURSAL
------------------------------------------------------------   
CREATE TABLE COM_POSTDISBURSAL 
   (	POSTDISB_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	POSTDISB_TYPE VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	POSTDISB_SNO CHAR(4 BYTE) NOT NULL ENABLE, 
	POSTDISB_VALUE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	POSTDISB_ID NUMBER(10,0) NOT NULL ENABLE
   );
   
------------------------------------------------------------
 --DDL for FINACLETOLAPS_CCPC_DETAILS
------------------------------------------------------------   
   
   CREATE TABLE FINACLETOLAPS_CCPC_DETAILS 
   (	CBSID VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	CASHWITHDRAW_NOOFTIMES VARCHAR2(5 BYTE), 
	CASHWITHDRAW_MAXAMT NUMBER(16,2), 
	CASHWITHDRAW_MINAMT NUMBER(16,2), 
	CASHWITHDRAW_TOTALAMT NUMBER(16,2)
   );
------------------------------------------------------------
 --DDL for FINACLETOLAPS_ONETIME_BILLS 
------------------------------------------------------------      
  CREATE TABLE FINACLETOLAPS_ONETIME_BILLS 
   (	CBSID VARCHAR2(15 BYTE), 
	ACCOUNTNUMBER VARCHAR2(15 BYTE), 
	OUTSTANDINGAMOUNT NUMBER(16,2), 
	SANCTIONEDAMT_LIMIT NUMBER(16,2), 
	ACCOUNTOPENEDDATE DATE, 
	ASSETCLASSIFICATION NUMBER(3,0), 
	ACCOUNTSTATUS CHAR(1 BYTE), 
	INTERESTAMOUNT NUMBER(16,2), 
	BILLNO VARCHAR2(15 BYTE), 
	BILLDATE DATE, 
	TYPEOFBILL CHAR(1 BYTE), 
	BILLCATEGORY CHAR(1 BYTE), 
	BILLCURRENCY CHAR(3 BYTE), 
	BILLAMOUNT NUMBER(16,2), 
	BILLCOLLPURDISCOUNT CHAR(1 BYTE), 
	BILLDUEDATE DATE, 
	BILLDISHONOREDDATE DATE, 
	OVERDUEAMOUNT NUMBER(16,2), 
	REALIZED CHAR(1 BYTE)
   ); 
------------------------------------------------------------
 --DDL for FINACLETOLAPS_ONETIME_CCTLOD
------------------------------------------------------------   
  CREATE TABLE FINACLETOLAPS_ONETIME_CCTLOD 
   (	CBSID VARCHAR2(15 BYTE), 
	ACCOUNTNUMBER VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	OUTSTANDINGAMOUNT NUMBER(16,2), 
	SANCTIONEDAMT_LIMIT NUMBER(16,2), 
	NOOFINSTALLMENTS NUMBER(5,0), 
	INSTALLMENT_EMIAMT NUMBER(16,2), 
	ACCOUNTOPENEDDATE DATE, 
	INSTALLMENTSTARTDATE DATE, 
	INSTALLMENTPERIODICITY CHAR(1 BYTE), 
	ASSETCLASSIFICATION NUMBER(3,0), 
	ACCOUNTSTATUS CHAR(1 BYTE), 
	INTERESTINCOME NUMBER(16,2), 
	OVERDUEAMOUNT NUMBER(16,2), 
	OVERDUESINCE VARCHAR2(15 BYTE), 
	MORTGAGED CHAR(1 BYTE), 
	MORTGAGEVALUE NUMBER(16,2), 
	GLCODE VARCHAR2(5 BYTE), 
	SCHEMETYPE VARCHAR2(10 BYTE), 
	CREDITTURNOVER NUMBER(16,2), 
	DEBITTURNOVER NUMBER(16,2), 
	NOOFCHEQUERETURNIN VARCHAR2(4 BYTE), 
	NOOFCHEQUERETURNOUT VARCHAR2(4 BYTE), 
	CHQRETURNCHARGES VARCHAR2(5 BYTE), 
	NPAPRINCIPALAMT NUMBER(16,2), 
	NPAINTERESTAMT NUMBER(16,2), 
	OVERDUETYPE VARCHAR2(5 BYTE)
   );
------------------------------------------------------------
 --DDL for FINACLETOLAPS_ONETIME_LC
------------------------------------------------------------    
     CREATE TABLE FINACLETOLAPS_ONETIME_LC 
   (	CBSID VARCHAR2(15 BYTE), 
	ACCOUNTNUMBER VARCHAR2(20 BYTE), 
	LCNUMBER VARCHAR2(15 BYTE), 
	TYPEOFLC CHAR(1 BYTE), 
	TERM CHAR(1 BYTE), 
	AMOUNTOFLC NUMBER(16,2), 
	COMMISSIONCHARGED NUMBER(16,2), 
	STATUS CHAR(1 BYTE)
   );
------------------------------------------------------------
 --DDL for LIMIT_MASTER
------------------------------------------------------------ 
CREATE TABLE LIMIT_MASTER 
   (	LIMIT_ID NUMBER(10,0) NOT NULL ENABLE, 
	LIMIT_FROM NUMBER(18,0), 
	LIMIT_TO NUMBER(18,0), 
	USR_CLASS NUMBER(10,0), 
	MAX_AMOUNT NUMBER(18,0), 
	FACILITY_ID NUMBER(10,0)
   ); 
------------------------------------------------------------
 --DDL for TEMP_MASTER
------------------------------------------------------------
 CREATE TABLE TEMP_MASTER 
   (	PRDINT_PRDCODE NUMBER(10,0) NOT NULL ENABLE, 
	PRDINT_INTTYPE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	PRDINT_SNO NUMBER(10,0) NOT NULL ENABLE, 
	PRD_AMTRANGEFROM NUMBER(18,2) NOT NULL ENABLE, 
	PRD_AMTRANGETO NUMBER(18,2) NOT NULL ENABLE
   );
------------------------------------------------------------
 --DDL for TEMP_CHILD
------------------------------------------------------------
  CREATE TABLE TEMP_CHILD 
   (	PRD_INTID NUMBER(10,0) NOT NULL ENABLE, 
	PRD_SNO NUMBER(10,0) NOT NULL ENABLE, 
	PRD_TERMFROM NUMBER(10,0), 
	PRD_TERMTO NUMBER(10,0), 
	PRD_BASERATE NUMBER(18,2), 
	PRD_ADJUST CHAR(10 BYTE), 
	PRD_INTEREST NUMBER(18,2), 
	PRD_INTERESTID NUMBER(10,0)
   );
------------------------------------------------------------
 --DDL for SUPPLIERDETAILS
------------------------------------------------------------
CREATE TABLE SUPPLIERDETAILS 
   (	ORG_CODE VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	SUPPLIER_SNO NUMBER(9,0) NOT NULL ENABLE, 
	SUPPLIER_TYPE NUMBER(9,0), 
	SUPPLIER_NAME VARCHAR2(60 BYTE), 
	SUPPLIER_ADDR1 VARCHAR2(60 BYTE), 
	SUPPLIER_ADDR2 VARCHAR2(60 BYTE), 
	SUPPLIER_CITY VARCHAR2(20 BYTE), 
	SUPPLIER_PINCODE VARCHAR2(6 BYTE), 
	SUPPLIER_STATE VARCHAR2(20 BYTE), 
	SUPPLIER_EMAIL VARCHAR2(60 BYTE), 
	SUPPLIER_PHONE VARCHAR2(60 BYTE), 
	SUPPLIER_CONT_PERS_NAME VARCHAR2(60 BYTE), 
	SUPPLIER_CONT_PERS_PHONE VARCHAR2(20 BYTE), 
	SUPPLIER_YEARS_OF_EXP NUMBER(10,0), 
	SUPPLIER_PREF_VENDOR NUMBER(10,0), 
	SUPPLIER_REMARK VARCHAR2(4000 BYTE)
   );
------------------------------------------------------------
 --DDL for SUBDOCUMENT_OLD1
------------------------------------------------------------
 CREATE TABLE SUBDOCUMENT_OLD1 
   (	DOC_SUBID NUMBER(10,0) NOT NULL ENABLE, 
	DOC_SUBALTERNATE VARCHAR2(50 BYTE), 
	DOC_SUBRULE VARCHAR2(2000 BYTE), 
	DOC_SUBIDENTIFY VARCHAR2(2 BYTE) NOT NULL ENABLE
   );
------------------------------------------------------------
 --DDL for STRESSRULEMAIN
------------------------------------------------------------
 CREATE TABLE STRESSRULEMAIN 
   (	STRESSMAIN_ID NUMBER(10,0) NOT NULL ENABLE, 
	STRESSMAIN_DESC VARCHAR2(200 BYTE) NOT NULL ENABLE
   );
------------------------------------------------------------
 --DDL for STRESS_BRULES
------------------------------------------------------------
  CREATE TABLE STRESS_BRULES 
   (	STRESS_BRULE NUMBER(10,0) NOT NULL ENABLE, 
	STRESS_SNO NUMBER(10,0) NOT NULL ENABLE, 
	STRESS_MODE CHAR(1 BYTE), 
	STRESS_TYPE CHAR(1 BYTE), 
	STRESS_RATE NUMBER(18,2), 
	STRESS_APPLYTO NUMBER(10,0), 
	STRESS_FORMULA NUMBER(10,0)
   );
------------------------------------------------------------
 --DDL for STEPUPRULES
------------------------------------------------------------
 CREATE TABLE STEPUPRULES 
   (	RULEID NUMBER(10,0) NOT NULL ENABLE, 
	LOANAMT NUMBER(18,2)
   );
------------------------------------------------------------
 --DDL for RISKMGMTPER
------------------------------------------------------------
  CREATE TABLE RISKMGMTPER 
   (	RSK_MONINCOME VARCHAR2(200 BYTE), 
	RSK_MONEXPENSES VARCHAR2(200 BYTE), 
	RSK_LESSFINEXP NUMBER(5,2), 
	RSK_LESSFINTAX NUMBER(5,2), 
	RSK_COLLLIQASSETS VARCHAR2(200 BYTE), 
	RSK_COLLNONLIQASSETS VARCHAR2(200 BYTE), 
	RSK_REALCOSTHOME NUMBER(5,2), 
	RSK_REALCOSTAUTO NUMBER(5,2), 
	RSK_REALCOSTBOAT NUMBER(5,2), 
	RSK_REALCOSTPER NUMBER(5,2), 
	RSK_REALCOSTLIQASSET NUMBER(5,2), 
	RSK_LESSLIABILITIES VARCHAR2(200 BYTE)
   );
------------------------------------------------------------
 --DDL for RISKMGMTCOM
------------------------------------------------------------
 CREATE TABLE RISKMGMTCOM 
   (	RISK_CODE VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	RISK_DESC VARCHAR2(100 BYTE), 
	RISK_RATIOS VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	RISK_EXE_FROM NUMBER(18,2), 
	RISK_EXE_TO NUMBER(18,2), 
	RISK_AVE_FROM NUMBER(18,2), 
	RISK_AVE_TO NUMBER(18,2), 
	RISK_POOR_FROM NUMBER(18,2), 
	RISK_POOR_TO NUMBER(18,2), 
	RISK_CODE_NATURE VARCHAR2(1 BYTE), 
	RISK_BS_IC VARCHAR2(2 BYTE), 
	RISK_GENCODE NUMBER(10,0) NOT NULL ENABLE
   ) ;
------------------------------------------------------------
 --DDL for RESULTS
------------------------------------------------------------
 CREATE TABLE RESULTS
   (	VOICE_APPNO VARCHAR2(20 BYTE), 
	VOICE_CTRLNO NUMBER(10,0), 
	VOICE_FILENAME VARCHAR2(100 BYTE), 
	VOICE_RECBY VARCHAR2(11 BYTE), 
	VOICE_RECON DATE
   );
------------------------------------------------------------
 --DDL for REPORTPROFILE
------------------------------------------------------------
  CREATE TABLE REPORTPROFILE 
   (	REP_USRID VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	REP_REPNAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	REP_PROFILENAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	REP_PARAM LONG NOT NULL ENABLE, 
	REP_REPDATE DATE, 
	REP_FRMAMT NUMBER(18,2), 
	REP_TOAMT NUMBER(18,2)
   )
------------------------------------------------------------
 --DDL for REPAYMENT
------------------------------------------------------------
CREATE TABLE REPAYMENT 
   (	APP_NO VARCHAR2(20 BYTE), 
	TERM NUMBER(10,0), 
	OPBAL NUMBER(18,0), 
	CHARGES NUMBER(18,0), 
	TOTCHARG NUMBER(18,0), 
	INTEREST NUMBER(18,0), 
	PRINCIPAL NUMBER(18,0), 
	AMTREC NUMBER(18,0), 
	CURRBAL NUMBER(18,0), 
	DUEDATE DATE, 
	DATEREC DATE
   ) ;
------------------------------------------------------------
 --DDL for REHABILATIONVIEW
------------------------------------------------------------
 CREATE TABLE REHABILATIONVIEW 
   (	REHAB_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	COMAPP_COMPANYID VARCHAR2(500 BYTE), 
	COMAPP_COMPANYNAME VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	REHAB_STATUS VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	REHAB_TYPE VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	REHAB_FROMDATE DATE NOT NULL ENABLE, 
	REHAB_TODATE DATE NOT NULL ENABLE
   ) ;
------------------------------------------------------------
 --DDL for REHABILATION
------------------------------------------------------------
  CREATE TABLE REHABILATION 
   (	REHAB_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	REHAB_FROMDATE DATE NOT NULL ENABLE, 
	REHAB_TODATE DATE NOT NULL ENABLE, 
	REHAB_STATUS VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	REHAB_TYPE VARCHAR2(1 BYTE) NOT NULL ENABLE
   ) ;
------------------------------------------------------------
 --DDL for LOS_NOTIFICATION
------------------------------------------------------------
 CREATE TABLE LOS_NOTIFICATION 
   (	NOTE_BCODE VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	NOTE_REQD CHAR(1 BYTE), 
	NOTE_BEFORE NUMBER(10,0), 
	NOTE_BODY LONG, 
	NOTE_TIME VARCHAR2(5 BYTE), 
	NOTE_CASH_RECPT CHAR(1 BYTE), 
	NOTE_CHEQUE_RECPT CHAR(1 BYTE)
   ) ;
------------------------------------------------------------
 --DDL for LOS_PROCESS
------------------------------------------------------------
CREATE TABLE LOS_PROCESS 
   (	PROC_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PROC_PYMT_MTH NUMBER(5,0) NOT NULL ENABLE, 
	PROC_CURR_PYMT_DUE_DATE DATE, 
	PROC_NOTIFY_DATE DATE, 
	PROC_PYMT_RECD_DATE DATE, 
	PROC_PYMT_AMT NUMBER(18,2), 
	PROC_PYMT_TYPE CHAR(1 BYTE), 
	PROC_CHECK_NO VARCHAR2(20 BYTE), 
	PROC_CREDIT_CARD_NO VARCHAR2(20 BYTE), 
	PROC_CREDIT_EXP_DATE DATE, 
	PROC_FLAG CHAR(1 BYTE), 
	PROC_LETTERS_FLAG CHAR(5 BYTE) NOT NULL ENABLE, 
	PROC_CURR_AMT_DUE NUMBER(18,2), 
	PROC_CHECK_BNKNAME VARCHAR2(50 BYTE), 
	PROC_EMI_INT_AMT NUMBER(18,2), 
	PROC_CARRYOVER_INT NUMBER(18,2), 
	PROC_CARRYOVER_EMI_INT NUMBER(18,2), 
	PROC_CARRYOVER_PENALTY NUMBER(18,2), 
	PROC_CARRYOVER_BAL NUMBER(18,2), 
	PROC_PAY_STATUS CHAR(1 BYTE), 
	PROC_CARRYOVER_CANCEL_FEE NUMBER(18,2), 
	CANCELDATE DATE, 
	CANCHKNO VARCHAR2(20 BYTE), 
	CANCHKDATE DATE, 
	PAYUSERID VARCHAR2(6 BYTE), 
	CANUSERID VARCHAR2(6 BYTE), 
	PROC_PAID_PENALTY NUMBER(18,2), 
	PROC_LATE_PAID_INT NUMBER(18,2)
   );
------------------------------------------------------------
 --DDL for LOS_REMINDERS
------------------------------------------------------------
 CREATE TABLE LOS_REMINDERS 
   (	REM_BCODE VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	REM_REMREQD CHAR(1 BYTE), 
	REM_REMTIME VARCHAR2(5 BYTE), 
	REM_BEFOREDELNOTICE NUMBER(10,0), 
	REM_FIRSTLETTERPERIOD NUMBER(10,0), 
	REM_SECONDLETTERPERIOD NUMBER(10,0), 
	REM_THIRDLETTERPERIOD NUMBER(10,0), 
	REM_FIRSTLETTER VARCHAR2(4000 BYTE), 
	REM_SECONDLETTER VARCHAR2(4000 BYTE), 
	REM_THIRDLETTER VARCHAR2(4000 BYTE), 
	REM_LATEFEE NUMBER(18,2), 
	REM_RETURNFEE NUMBER(18,2), 
	REM_EARLYPAY CHAR(1 BYTE), 
	REM_PENALTYTYPE CHAR(1 BYTE), 
	REM_PENALTYVAL NUMBER(18,2), 
	REM_INTTYPE CHAR(1 BYTE), 
	REM_INTCOMP CHAR(1 BYTE), 
	REM_LATEINT NUMBER(18,2), 
	REM_GRACEPERIOD NUMBER(10,0), 
	REM_DELQOPTIONS CHAR(1 BYTE), 
	REM_DELQLETTERTIME VARCHAR2(5 BYTE), 
	REM_DELQLETTERAFTER VARCHAR2(3 BYTE), 
	REM_EXTORGNAME VARCHAR2(100 BYTE), 
	REM_EXTADD1 VARCHAR2(100 BYTE), 
	REM_EXTADD2 VARCHAR2(100 BYTE), 
	REM_EXTCITY VARCHAR2(50 BYTE), 
	REM_EXTSTATE VARCHAR2(20 BYTE), 
	REM_EXTPINCODE VARCHAR2(20 BYTE), 
	REM_EXTMAIL VARCHAR2(50 BYTE), 
	REM_EXTPHONE VARCHAR2(20 BYTE), 
	REM_DELQLETTER VARCHAR2(4000 BYTE)
   )
------------------------------------------------------------
 --DDL for LOS_SERVICE
------------------------------------------------------------
CREATE TABLE LOS_SERVICE 
   (	SERV_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	SERV_DUE_DATE DATE, 
	SERV_LAST_PYMT_MTH NUMBER(5,0), 
	SERV_CURR_PYMT_MTH NUMBER(5,0), 
	SERV_NEXT_PYMT_MTH NUMBER(5,0), 
	SERV_TOTAL_PYMT_RECD NUMBER(18,2), 
	SERV_CURR_BAL_DUE NUMBER(18,2), 
	SERV_NET_BAL_DUE NUMBER(18,2)
   )
------------------------------------------------------------
 --DDL for LIMIT_REGISTER
------------------------------------------------------------
 CREATE TABLE LIMIT_REGISTER 
   (	REGISTER_ID NUMBER NOT NULL ENABLE, 
	CUSTOMER_ID NUMBER, 
	CUSTOMER_TYPE CHAR(1 BYTE), 
	REGISTER_DATE DATE, 
	SANCTIONED_BY VARCHAR2(100 BYTE), 
	NATURE_OF_LIMIT VARCHAR2(100 BYTE), 
	AMOUNT_OF_LIMIT NUMBER(18,0), 
	MARGIN NUMBER(18,0), 
	INTEREST_RATE NUMBER(18,0), 
	SECURITY VARCHAR2(100 BYTE), 
	REMARKS VARCHAR2(1000 BYTE), 
	MODIFIED_BY VARCHAR2(100 BYTE), 
	MODIFIED_DATE DATE, 
	ACCOUNT_NO VARCHAR2(20 BYTE), 
	EXP_DATE DATE, 
	LIMIT_TYPE VARCHAR2(2 BYTE)
   ) ;
------------------------------------------------------------
 --DDL for APPAUDITORNOTES
------------------------------------------------------------
CREATE TABLE APPAUDITORNOTES 
   (	AUD_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	AUD_USRID VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	AUD_TEXT LONG, 
	AUD_MODDATE DATE
   );
------------------------------------------------------------
 --DDL for APPAUDITORREMARKS
------------------------------------------------------------
 CREATE TABLE APPAUDITORREMARKS 
   (	APP_AUDITAPPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	APP_AUDITID NUMBER(10,0) NOT NULL ENABLE, 
	APP_AUDITTYPE CHAR(1 BYTE) NOT NULL ENABLE, 
	APP_AUDITREMARKS VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	APP_AUDDATETIME DATE NOT NULL ENABLE
   ) ;
------------------------------------------------------------
 --DDL for APP_HISTORY
------------------------------------------------------------
 CREATE TABLE APP_HISTORY 
   (	ORG_CODE VARCHAR2(15 BYTE), 
	ORG_APPSCODE VARCHAR2(30 BYTE), 
	APP_NO VARCHAR2(20 BYTE), 
	BRANCH_REFNO VARCHAR2(25 BYTE), 
	RECEIPT_DT DATE, 
	PERAPP_ID NUMBER(10,0), 
	PERAPP_NAME VARCHAR2(150 BYTE), 
	AMT_APPLIED VARCHAR2(10 BYTE), 
	AMT_SANCTION VARCHAR2(10 BYTE), 
	RAH_SEND_DT DATE, 
	RAH_RECE_DT DATE, 
	LEGAL_SEND_DT DATE, 
	LEGAL_RECE_DT DATE, 
	DELI_SEND_DT DATE, 
	DELI_RECE_DT DATE, 
	APPR_PROC_DATE DATE, 
	SANC_REJ_DATE DATE, 
	BRANCH_SEND_DT DATE, 
	SANC_STATUS VARCHAR2(2 BYTE), 
	VALUATION_SEND_DT DATE, 
	VALUATION_RECE_DT DATE, 
	LOANAC_NO VARCHAR2(10 BYTE), 
	DISBURSE_DT DATE
   );
------------------------------------------------------------
 --DDL for APP_ENCLOSURES
------------------------------------------------------------
CREATE TABLE APP_ENCLOSURES 
   (	APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	ENCLOSURE_SLNO NUMBER(18,0), 
	ENCLOSURE_COMMENTS VARCHAR2(100 BYTE)
   );
------------------------------------------------------------
 --DDL for BRANCH_REF_COMMENTS
------------------------------------------------------------
CREATE TABLE BRANCH_REF_COMMENTS 
   (	ORG_CODE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	APP_NO VARCHAR2(20 BYTE), 
	BRANCH_REF_NO VARCHAR2(50 BYTE), 
	BRANCH_REF_SLNO NUMBER(18,0) NOT NULL ENABLE, 
	BRANCH_REF_COMMENTS LONG, 
	BRANCH_REF_USERID VARCHAR2(20 BYTE), 
	BRANCH_REF_DATE DATE
   );
------------------------------------------------------------
 --DDL for COM_BANKING_DTAUG13
------------------------------------------------------------
CREATE TABLE COM_BANKING_DT_AUG13 
   (	COMBK_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	COMBK_ID NUMBER(10,0) NOT NULL ENABLE, 
	COMBK_BANKNAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	COMBK_SHAREFUNDEXIST NUMBER(18,2), 
	COMBK_SHAREFUNDPROP NUMBER(18,2), 
	COMBK_SHARENONFUNDEXIST NUMBER(18,2), 
	COMBK_SHARENONFUNDPROP NUMBER(18,2), 
	COMBK_LMTFUNDEXIST NUMBER(18,2), 
	COMBK_LMTFUNDPROP NUMBER(18,2), 
	COMBK_LMTNONFUNDEXIST NUMBER(18,2), 
	COMBK_LMTNONFUNDPROP NUMBER(18,2), 
	COMBK_OSFUNDEXIST NUMBER(18,2), 
	COMBK_OSFUNDPROP NUMBER(18,2), 
	COMBK_OSNONFUNDEXIST NUMBER(18,2), 
	COMBK_OSNONFUNDPROP NUMBER(18,2), 
	COMBK_OVERDUE NUMBER(18,2), 
	COMBK_TYPE CHAR(10 BYTE) NOT NULL ENABLE
   ) ;
------------------------------------------------------------
 --DDL for COM_BANKING_DTAUG13
------------------------------------------------------------
 CREATE TABLE COM_BANKING_DTAUG13 
   (	COMBK_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	COMBK_ID NUMBER(10,0) NOT NULL ENABLE, 
	COMBK_BANKNAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	COMBK_SHAREFUNDEXIST NUMBER(18,2), 
	COMBK_SHAREFUNDPROP NUMBER(18,2), 
	COMBK_SHARENONFUNDEXIST NUMBER(18,2), 
	COMBK_SHARENONFUNDPROP NUMBER(18,2), 
	COMBK_LMTFUNDEXIST NUMBER(18,2), 
	COMBK_LMTFUNDPROP NUMBER(18,2), 
	COMBK_LMTNONFUNDEXIST NUMBER(18,2), 
	COMBK_LMTNONFUNDPROP NUMBER(18,2), 
	COMBK_OSFUNDEXIST NUMBER(18,2), 
	COMBK_OSFUNDPROP NUMBER(18,2), 
	COMBK_OSNONFUNDEXIST NUMBER(18,2), 
	COMBK_OSNONFUNDPROP NUMBER(18,2), 
	COMBK_OVERDUE NUMBER(18,2), 
	COMBK_TYPE CHAR(10 BYTE) NOT NULL ENABLE
   );
------------------------------------------------------------
 --DDL for COM_BANKING_DT2
------------------------------------------------------------
 CREATE TABLE COM_BANKING_DT2 
   (	COMBK_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	COMBK_ID NUMBER(10,0) NOT NULL ENABLE, 
	COMBK_BANKNAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	COMBK_PERSHAREFUNDED NUMBER(18,2), 
	COMBK_PERSHARENONFUNDED NUMBER(18,2), 
	COMBK_LMTFUNDED NUMBER(18,2), 
	COMBK_LMTNONFUNDED NUMBER(18,2), 
	COMBK_OSFUNDED NUMBER(18,2), 
	COMBK_OSNONFUNDED NUMBER(18,2), 
	COMBK_OVERDUE NUMBER(18,2), 
	COMBK_TYPE CHAR(10 BYTE) NOT NULL ENABLE
   );
------------------------------------------------------------
 --DDL for COM_BANKING_NEW
------------------------------------------------------------
CREATE TABLE COM_BANKING_NEW 
   (	COMBK_APPNO VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	COMBK_ID NUMBER(10,0) NOT NULL ENABLE, 
	COMBK_BANKNAME VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	COMBK_EXISTFUNDEDSHARE NUMBER(18,0), 
	COMBK_EXISTNONFUNDEDSHARE NUMBER(18,0), 
	COMBK_PROPFUNDEDSHARE NUMBER(18,0), 
	COMBK_PROPNONFUNDEDSHARE NUMBER(18,2), 
	COMBK_LMTFUNDED NUMBER(18,2), 
	COMBK_LMTNONFUNDED NUMBER(18,2), 
	COMBK_PROPLMTFUNDED NUMBER(18,0), 
	COMBK_PROPLMTNONFUNDED NUMBER(18,0), 
	COMBK_OSFUNDED NUMBER(18,2), 
	COMBK_OSNONFUNDED NUMBER(18,2), 
	COMBK_OVERDUE NUMBER(18,2), 
	COMBK_TYPE CHAR(1 BYTE) NOT NULL ENABLE
   );
------------------------------------------------------------
 --DDL for APPLICATION_DISPOSAL_REGISTER
------------------------------------------------------------
CREATE TABLE APPLICATION_DISPOSAL_REGISTER 
   (	REGISTER_ID NUMBER NOT NULL ENABLE, 
	CUSTOMER_ID NUMBER, 
	CUSTOMER_TYPE CHAR(1 BYTE), 
	RECEIPT_DATE DATE, 
	DISPOSAL_PURPOSE VARCHAR2(500 BYTE), 
	APPLICATION_SCHEME VARCHAR2(500 BYTE), 
	LOAN_AMOUNT NUMBER(18,0), 
	SANCTION_DATE DATE, 
	RETURN_DATE DATE, 
	REJECTION_DATE DATE, 
	REMARKS VARCHAR2(1000 BYTE), 
	MODIFIED_BY VARCHAR2(100 BYTE), 
	MODIFIED_DATE DATE
   );
------------------------------------------------------------
 --DDL for FIN_ACTUALS
------------------------------------------------------------
 CREATE TABLE FIN_ACTUALS 
   (	APPNO VARCHAR2(20 BYTE), 
	ACT_ROWID NUMBER(10,0), 
	ACT_VALUES NUMBER(18,2), 
	ACT_YEAR DATE
   ) ;
------------------------------------------------------------
 --DDL for FIN_ESTIMATES
------------------------------------------------------------
 CREATE TABLE FIN_ESTIMATES 
   (	APPNO VARCHAR2(20 BYTE), 
	EST_ROWID NUMBER(10,0), 
	EST_VALUES NUMBER(18,2), 
	EST_YEAR DATE
   );
------------------------------------------------------------
 --DDL for ODDEMOGRAPHICS
------------------------------------------------------------
  CREATE TABLE ODDEMOGRAPHICS 
   (	OD_APPNO VARCHAR2(20 BYTE), 
	OD_EMPNAME VARCHAR2(50 BYTE), 
	OD_ECNO VARCHAR2(20 BYTE), 
	OD_CADRE VARCHAR2(20 BYTE), 
	OD_DESIG VARCHAR2(20 BYTE), 
	OD_BRANCH VARCHAR2(20 BYTE), 
	OD_JOINDATE DATE, 
	OD_DOB DATE, 
	OD_AGE NUMBER(10,0), 
	OD_PFNOMINEENAME VARCHAR2(50 BYTE), 
	OD_PFNOMINRELATION VARCHAR2(50 BYTE), 
	OD_GRNOMINEENAME VARCHAR2(50 BYTE), 
	OD_GRNOMINRELATION VARCHAR2(50 BYTE), 
	OD_PRESENTADDRESS VARCHAR2(50 BYTE), 
	OD_PERMADDRESS VARCHAR2(50 BYTE), 
	OD_PRESENTPHONE VARCHAR2(20 BYTE), 
	OD_PERMPHONE VARCHAR2(20 BYTE)
   );
------------------------------------------------------------
 --DDL for ODAPPLICATIONS
------------------------------------------------------------
  CREATE TABLE ODAPPLICATIONS 
   (	ODAPP_APPNO VARCHAR2(20 BYTE), 
	ODAPP_CREATEDATE DATE, 
	ODAPP_USER VARCHAR2(50 BYTE), 
	ODAPP_REQAMT VARCHAR2(50 BYTE), 
	ODAPP_INTRATE NUMBER(10,0), 
	ODAPP_TERMS NUMBER(10,0), 
	ODAPP_STATUS VARCHAR2(50 BYTE), 
	ODAPP_APPROVEDDATE DATE, 
	ODAPP_APPROVEDBY VARCHAR2(50 BYTE)
   );
------------------------------------------------------------
 --DDL for PER_POSTDISBURSEMENT
------------------------------------------------------------
 CREATE TABLE PER_POSTDISBURSEMENT 
   (	POST_APPNO VARCHAR2(20 BYTE), 
	POST_DATE DATE, 
	POST_ADDRESS VARCHAR2(4000 BYTE), 
	POST_DISPDATE DATE, 
	POST_DISPAMOUNT VARCHAR2(50 BYTE), 
	POST_DISPMODE VARCHAR2(50 BYTE), 
	POST_PRESENTOSBAL VARCHAR2(50 BYTE), 
	POST_OVERDUE VARCHAR2(50 BYTE), 
	POST_INVOICE VARCHAR2(3 BYTE), 
	POST_INVOICENO VARCHAR2(50 BYTE), 
	POST_INVDATE DATE, 
	POST_INVISSUED VARCHAR2(50 BYTE), 
	POST_RECEIPTNO VARCHAR2(50 BYTE), 
	POST_RECEIPTDATE DATE, 
	POST_DESCRIPTION VARCHAR2(100 BYTE), 
	POST_MAKE VARCHAR2(50 BYTE), 
	POST_VECTYPE VARCHAR2(50 BYTE), 
	POST_VECMAKE VARCHAR2(50 BYTE), 
	POST_VECREGNO VARCHAR2(50 BYTE), 
	POST_VECINSPECTION VARCHAR2(3 BYTE), 
	POST_VECINSDATE DATE, 
	POST_INSNAME VARCHAR2(50 BYTE), 
	POST_VALID DATE, 
	POST_BANKCLAUSE VARCHAR2(3 BYTE), 
	POST_COMPREHENSIVE VARCHAR2(3 BYTE), 
	POST_LOANAVAIL VARCHAR2(3 BYTE), 
	POST_HOUSEADD VARCHAR2(4000 BYTE), 
	POST_STATUS VARCHAR2(50 BYTE), 
	POST_OCCUPATION VARCHAR2(1 BYTE), 
	POST_VALREPORT VARCHAR2(50 BYTE), 
	POST_VALDATE DATE, 
	POST_INSTAKEN DATE, 
	POST_DOCDATE DATE, 
	POST_LAD VARCHAR2(50 BYTE), 
	POST_COMMENTS VARCHAR2(4000 BYTE), 
	POST_PLACE VARCHAR2(50 BYTE), 
	POST_SIGNDATE DATE, 
	POST_NAME VARCHAR2(50 BYTE), 
	POST_DESIGNATION VARCHAR2(50 BYTE), 
	POST_CHEQUE VARCHAR2(50 BYTE), 
	POST_FAVOUR VARCHAR2(50 BYTE), 
	POST_COLOR VARCHAR2(50 BYTE), 
	POST_MANF VARCHAR2(50 BYTE), 
	POST_ENGINE VARCHAR2(50 BYTE), 
	POST_CHASIS VARCHAR2(50 BYTE), 
	POST_VECCOLOR VARCHAR2(50 BYTE), 
	POST_VECCONDITION VARCHAR2(50 BYTE), 
	POST_TTO VARCHAR2(3 BYTE), 
	POST_RTO VARCHAR2(3 BYTE), 
	POST_UNICARE VARCHAR2(3 BYTE), 
	POST_PURPOSE VARCHAR2(100 BYTE), 
	POST_LOANAMT VARCHAR2(50 BYTE), 
	POST_SANCDATE DATE, 
	POST_EAST VARCHAR2(50 BYTE), 
	POST_WEST VARCHAR2(50 BYTE), 
	POST_NORTH VARCHAR2(50 BYTE), 
	POST_SOUTH VARCHAR2(50 BYTE), 
	POST_INS VARCHAR2(50 BYTE), 
	POST_INS1 VARCHAR2(50 BYTE)
   );
------------------------------------------------------------
 --DDL for STATIC_VALUESET
------------------------------------------------------------
 CREATE TABLE STATIC_VALUESET 
   (	VALUE_SETID NUMBER, 
	VALUSE_SET_NAME VARCHAR2(100 BYTE)
   );
------------------------------------------------------------
 --DDL for STATIC_VALUE
------------------------------------------------------------
CREATE TABLE STATIC_VALUE 
   (	STATIC_VALUE_ID NUMBER, 
	VALUE_SET_ID NUMBER, 
	STATIC_VALUE VARCHAR2(50 BYTE), 
	STATIC_VAL_DES VARCHAR2(300 BYTE), 
	DISPLAY_ORDER VARCHAR2(100 BYTE), 
	ACTIVE VARCHAR2(10 BYTE)
   );
------------------------------------------------------------
 --DDL for SSI_STOCK
------------------------------------------------------------
  CREATE TABLE SSI_STOCK 
   (	STOC_APPNO VARCHAR2(20 BYTE), 
	STOC_APPLNT VARCHAR2(1 BYTE), 
	STOC_ID NUMBER(10,0), 
	STOC_SERIALNO NUMBER(10,0), 
	STOC_DESC VARCHAR2(50 BYTE), 
	STOC_SHAREVAL NUMBER(18,0), 
	STOC_NOOFSHARES NUMBER(10,0), 
	STOC_ISCOLL VARCHAR2(1 BYTE)
   );
------------------------------------------------------------
 --DDL for COM_YIELD
------------------------------------------------------------
 CREATE TABLE COM_YIELD 
   (	YIELD_APPNO VARCHAR2(20 BYTE), 
	YEILD_ID NUMBER(10,0), 
	YIELD_FROMDATE DATE, 
	YIELD_TODATE DATE, 
	YIELD_RATE NUMBER(18,2)
   );
------------------------------------------------------------
 --DDL for TOOLBAR_USERS
------------------------------------------------------------
 CREATE TABLE TOOLBAR_USERS 
   (	USR_ID VARCHAR2(15 BYTE), 
	SCREEN_MODULE NUMBER(10,0), 
	SCREEN_ID NUMBER(10,0)
   );
------------------------------------------------------------
 --DDL for MONITORING_SETALERTS
------------------------------------------------------------
 CREATE TABLE MONITORING_SETALERTS 
   (	ALERT_ID NUMBER(3,0), 
	ALERTTYPE NUMBER(3,0), 
	MIN_PERCENTAGE NUMBER(20,0), 
	MAX_PERCENTAGE NUMBER(20,0), 
	ASSETCLASSIFICATION NUMBER(3,0)
   )
------------------------------------------------------------
 --DDL for MON_INSTALLMENT
------------------------------------------------------------
CREATE TABLE MON_INSTALLMENT 
   (	INSTALL_CBSID VARCHAR2(16 BYTE), 
	INSTALL_ACCNO VARCHAR2(16 BYTE), 
	INSTALL_AMOUNT NUMBER(18,2), 
	INSTALL_DUEDATE DATE, 
	INSTALL_ACCFLAG VARCHAR2(5 BYTE)
   )
------------------------------------------------------------
 --DDL for MON_INSTALLMENTREGISTER
------------------------------------------------------------
CREATE TABLE MON_INSTALLMENTREGISTER 
   (	INTSTALLREG_ACCNO VARCHAR2(20 BYTE), 
	INTSTALLREG_SNO VARCHAR2(3 BYTE), 
	INTSTALL_AMT NUMBER(18,2), 
	INTSTALL_DUEDATE DATE, 
	INTSTALL_PAIDDATE DATE, 
	MODIFIED_BY VARCHAR2(50 BYTE), 
	MODIFIED_DATE DATE
   ) 
------------------------------------------------------------
 --DDL for MON_GUARANTOR_REGISTER
------------------------------------------------------------

  CREATE TABLE UBILAS1.MON_GUARANTOR_REGISTER 
   (	CUST_ID VARCHAR2(30 BYTE), 
	FIL_SNO VARCHAR2(2 BYTE), 
	FIL_ACCOUNTNO VARCHAR2(20 BYTE), 
	FIL_TYPE_APPLICANT VARCHAR2(75 BYTE), 
	FIL_APPLICANT_NAME VARCHAR2(75 BYTE), 
	MODIFIED_BY VARCHAR2(50 BYTE), 
	MODIFIED_DATE DATE
   );
------------------------------------------------------------
 --DDL for MON_RENEWALREGISTER
------------------------------------------------------------
  CREATE TABLE MON_RENEWALREGISTER 
   (	RENEWAL_ACCNO VARCHAR2(20 BYTE), 
	RENEWAL_SNO VARCHAR2(3 BYTE), 
	RENEWAL_SANCTIONEDDATE DATE, 
	RENEWAL_RENEWALDATE DATE, 
	MODIFIED_BY VARCHAR2(50 BYTE), 
	MODIFIED_DATE DATE
   );
------------------------------------------------------------
 --DDL for MON_INTERESTREGISTER
------------------------------------------------------------
CREATE TABLE MON_INTERESTREGISTER 
   (	INTREG_ACCNO VARCHAR2(20 BYTE), 
	INTREG_SNO VARCHAR2(5 BYTE), 
	INTREG_INTERESTAMT NUMBER(18,2), 
	INTREG_PENALAMT NUMBER(18,2), 
	INTREG_TOTALAMT NUMBER(18,2), 
	INTREG_APPDATE DATE, 
	INTREG_SERVICEDATE DATE, 
	MODIFIED_BY VARCHAR2(50 BYTE), 
	MODIFIED_DATE DATE
   );
------------------------------------------------------------
 --DDL for MON_INTEREST
------------------------------------------------------------
  CREATE TABLE MON_INTEREST 
   (	INT_CBSID VARCHAR2(16 BYTE), 
	INT_ACCNO VARCHAR2(16 BYTE), 
	INT_INTAMT NUMBER(18,2), 
	INT_APPDATE DATE, 
	INT_SERVICEDATE DATE
   );
------------------------------------------------------------
 --DDL for STATUSPAGE
------------------------------------------------------------
CREATE TABLE STATUSPAGE 
   (	APP_NO VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	OBSERVATION VARCHAR2(4000 BYTE), 
	COMPLIANCE VARCHAR2(4000 BYTE), 
	ACTIONPLAN VARCHAR2(4000 BYTE), 
	STATUTORYDATE DATE
   );
------------------------------------------------------------
 --DDL for CAD_BUSRISKS
------------------------------------------------------------
CREATE TABLE CAD_BUSRISKS 
   (	CAD_APPNO VARCHAR2(20 BYTE), 
	CAD_BUSRISK VARCHAR2(100 BYTE), 
	CAD_CYCLE VARCHAR2(100 BYTE), 
	CAD_CYCLE_EXPLN VARCHAR2(4000 BYTE), 
	CAD_DEMAND VARCHAR2(100 BYTE), 
	CAD_DEMAND_EXPLN VARCHAR2(4000 BYTE), 
	CAD_SUPPLY VARCHAR2(100 BYTE), 
	CAD_SUPPLY_EXPLN VARCHAR2(4000 BYTE), 
	CAD_CAPACITY VARCHAR2(100 BYTE), 
	CAD_CAPACITY_EXPLN VARCHAR2(4000 BYTE), 
	CAD_COMPETITIVE VARCHAR2(100 BYTE), 
	CAD_COMPETITIVE_EXPLN VARCHAR2(4000 BYTE), 
	CAD_POLICY VARCHAR2(100 BYTE), 
	CAD_POLICY_EXPLN VARCHAR2(4000 BYTE), 
	CAD_FISCAL VARCHAR2(100 BYTE), 
	CAD_FISCAL_EXPLN VARCHAR2(4000 BYTE), 
	CAD_ANYNEWS VARCHAR2(100 BYTE), 
	CAD_ANYNEWS_EXPLN VARCHAR2(4000 BYTE), 
	CAD_COMPANYRISK VARCHAR2(100 BYTE), 
	CAD_PROMOTERS VARCHAR2(100 BYTE), 
	CAD_PROMOTERS_EXPLN VARCHAR2(4000 BYTE), 
	CAD_INDUSTRY VARCHAR2(100 BYTE), 
	CAD_INDUSTRY_EXPLN VARCHAR2(4000 BYTE), 
	CAD_TREND VARCHAR2(100 BYTE), 
	CAD_TREND_EXPLN VARCHAR2(4000 BYTE), 
	CAD_STABILITY VARCHAR2(100 BYTE), 
	CAD_STABILITY_EXPLN VARCHAR2(4000 BYTE), 
	CAD_INITIATIVE VARCHAR2(100 BYTE), 
	CAD_INITIATIVE_EXPLN VARCHAR2(4000 BYTE), 
	CAD_RELEVENCE VARCHAR2(100 BYTE), 
	CAD_RELEVENCE_EXPLN VARCHAR2(4000 BYTE), 
	CAD_RISK_COMMENTS VARCHAR2(4000 BYTE), 
	CAD_ENCL_NOTE VARCHAR2(50 BYTE), 
	CAD_GRADE VARCHAR2(50 BYTE), 
	CAD_GRADE_DATE DATE, 
	CAD_DUETO VARCHAR2(100 BYTE), 
	CAD_IND_AVERAGE VARCHAR2(50 BYTE), 
	CAD_REVEAL VARCHAR2(4000 BYTE), 
	CAD_RISKBUSINESS VARCHAR2(4000 BYTE), 
	CAD_FINCOMPANY VARCHAR2(4000 BYTE)
   )
------------------------------------------------------------
 --DDL for CAD_EXPOSURE
------------------------------------------------------------
  CREATE TABLE CAD_EXPOSURE 
   (	CAD_APPNO VARCHAR2(20 BYTE), 
	CAD_REFNO VARCHAR2(100 BYTE), 
	CAD_DATE DATE, 
	CAD_NOTE VARCHAR2(100 BYTE), 
	CAD_ENCLOSEDDATE DATE, 
	CAD_RECDDATE DATE, 
	CAD_DESIGNATION VARCHAR2(100 BYTE), 
	CAD_MANAGER VARCHAR2(100 BYTE), 
	CAD_PORTPOLIO VARCHAR2(100 BYTE), 
	CAD_SUBSECTOR VARCHAR2(100 BYTE), 
	CAD_ECORISK VARCHAR2(100 BYTE), 
	CAD_BANK VARCHAR2(100 BYTE), 
	CAD_DATE1 DATE, 
	CAD_SECTOR VARCHAR2(100 BYTE), 
	CAD_NPA VARCHAR2(100 BYTE), 
	CAD_DATE2 DATE, 
	CAD_NPASECOR VARCHAR2(100 BYTE), 
	CAD_DATE3 DATE, 
	CAD_NPATOTAL VARCHAR2(100 BYTE), 
	CAD_DATE4 DATE, 
	CAD_TOTAL VARCHAR2(100 BYTE), 
	CAD_DATE5 DATE, 
	CAD_ZONE VARCHAR2(100 BYTE), 
	CAD_DATE6 DATE, 
	CAD_SHARE VARCHAR2(100 BYTE), 
	CAD_NPAZONE VARCHAR2(100 BYTE), 
	CAD_DATE7 DATE, 
	CAD_WITHIN VARCHAR2(100 BYTE), 
	CAD_DATE8 DATE, 
	CAD_IND VARCHAR2(100 BYTE), 
	CAD_DATE9 DATE, 
	CAD_VIS VARCHAR2(100 BYTE), 
	CAD_DATE10 DATE, 
	CAD_ECONOMIC VARCHAR2(100 BYTE), 
	CAD_SECTOR_NAME VARCHAR2(100 BYTE)
   ) ;
------------------------------------------------------------
 --DDL for CAD_KEYFINANCIALS
------------------------------------------------------------
CREATE TABLE CAD_KEYFINANCIALS 
   (	CAD_APPNO VARCHAR2(20 BYTE), 
	CAD_ID NUMBER(18,0), 
	CAD_DESC VARCHAR2(50 BYTE), 
	CAD_SALES_GROWTH VARCHAR2(50 BYTE), 
	CAD_SALES_VLTY VARCHAR2(50 BYTE), 
	CAD_OPM VARCHAR2(50 BYTE), 
	CAD_OPM_VLTY VARCHAR2(50 BYTE), 
	CAD_INT_COVER VARCHAR2(50 BYTE), 
	CAD_DEBT_COVER VARCHAR2(50 BYTE), 
	CAD_CURRENT VARCHAR2(50 BYTE), 
	CAD_DEBTEQUITY VARCHAR2(50 BYTE), 
	CAD_WCCYCLE VARCHAR2(50 BYTE)
   );
------------------------------------------------------------
 --DDL for CAD_NEWPROJECT
------------------------------------------------------------
CREATE TABLE CAD_NEWPROJECT 
   (	CAD_APPNO VARCHAR2(20 BYTE), 
	CAD_ID NUMBER(18,0), 
	CAD_DESC VARCHAR2(50 BYTE), 
	CAD_PROJCOST VARCHAR2(50 BYTE), 
	CAD_FUNDMEANS VARCHAR2(50 BYTE), 
	CAD_CAPACITYUTIL VARCHAR2(50 BYTE), 
	CAD_DEMSUPGAP VARCHAR2(50 BYTE), 
	CAD_DSCR VARCHAR2(50 BYTE)
   )
------------------------------------------------------------
 --DDL for CAD_OTHERDETAILS
------------------------------------------------------------
CREATE TABLE CAD_OTHERDETAILS 
   (	CAD_APPNO VARCHAR2(20 BYTE), 
	CAD_FINRISK VARCHAR2(100 BYTE), 
	CAD_FINANALYSIS VARCHAR2(4000 BYTE), 
	CAD_FINGROUP VARCHAR2(50 BYTE), 
	CAD_SINGLE VARCHAR2(50 BYTE), 
	CAD_EXPOSURE VARCHAR2(50 BYTE), 
	CAD_CIRCULAR VARCHAR2(25 BYTE), 
	CAD_DATE1 DATE, 
	CAD_DATE2 DATE, 
	CAD_SAFETY VARCHAR2(50 BYTE), 
	CAD_MONEY VARCHAR2(50 BYTE), 
	CAD_SIZE VARCHAR2(50 BYTE), 
	CAD_DATE3 DATE, 
	CAD_INDICATE VARCHAR2(25 BYTE), 
	CAD_OTHER VARCHAR2(150 BYTE), 
	CAD_OBSERVATION VARCHAR2(4000 BYTE), 
	CAD_RBI VARCHAR2(4000 BYTE), 
	CAD_MAJOR VARCHAR2(4000 BYTE), 
	CAD_NOTE VARCHAR2(4000 BYTE), 
	CAD_RATING VARCHAR2(50 BYTE), 
	CAD_AGENCY VARCHAR2(50 BYTE), 
	CAD_DEBIT VARCHAR2(50 BYTE), 
	CAD_CONDUCT VARCHAR2(4000 BYTE)
   )
------------------------------------------------------------
 --DDL for CAD_PEERCOMPARE
------------------------------------------------------------

  CREATE TABLE CAD_PEERCOMPARE 
   (	CAD_APPNO VARCHAR2(20 BYTE), 
	CAD_ID NUMBER(18,0), 
	CAD_DESC VARCHAR2(50 BYTE), 
	CAD_NWTL VARCHAR2(50 BYTE), 
	CAD_WCTA VARCHAR2(50 BYTE), 
	CAD_RETA VARCHAR2(50 BYTE), 
	CAD_SALESTA VARCHAR2(50 BYTE), 
	CAD_EBITTA VARCHAR2(50 BYTE), 
	CAD_TDNW VARCHAR2(50 BYTE), 
	CAD_OCFSALES VARCHAR2(50 BYTE)
   )
------------------------------------------------------------
 --DDL for CBS_LAPSINFO
------------------------------------------------------------
 CREATE TABLE CBS_LAPSINFO 
   (	CBSACCOUNTNUMBER VARCHAR2(20 BYTE), 
	CBSID VARCHAR2(20 BYTE), 
	LAPSID VARCHAR2(20 BYTE), 
	LAPSAPPNO VARCHAR2(20 BYTE)
   );
------------------------------------------------------------
 --DDL for COM_CRDFACILITIES
------------------------------------------------------------

  CREATE TABLE COM_CRDFACILITIES 
   (	FAC_APPNO VARCHAR2(20 BYTE), 
	FAC_NATURE VARCHAR2(50 BYTE), 
	FAC_EXISTLIMIT NUMBER(18,2), 
	FAC_LIABILITIES NUMBER(18,2), 
	FAC_AMTDUE NUMBER(18,2), 
	FAC_REQAMT NUMBER(18,2), 
	FAC_RECAMT NUMBER(18,2), 
	FAC_APPAMT NUMBER(18,2), 
	FAC_INTRATE NUMBER(6,2), 
	FAC_MARGIN NUMBER(18,2), 
	FAC_REMARKS VARCHAR2(200 BYTE), 
	FAC_SNO NUMBER(10,0)
   )
------------------------------------------------------------
 --DDL for COM_CRDHISTORY
------------------------------------------------------------
 CREATE TABLE COM_CRDHISTORY 
   (	CRDHIST_APPNO VARCHAR2(20 BYTE), 
	CRDHIST_COMPNAME VARCHAR2(100 BYTE), 
	CRDHIST_PROMNAME VARCHAR2(100 BYTE), 
	CRDHIST_BRANCH VARCHAR2(100 BYTE), 
	CRDHIST_BORROWAMT NUMBER(18,2), 
	CRDHIST_OUTAMT NUMBER(18,2), 
	CRDHIST_OPL VARCHAR2(4 BYTE)
   )
------------------------------------------------------------
 --DDL for COM_CRDMAIN
------------------------------------------------------------
 CREATE TABLE "UBILAS1"."COM_CRDMAIN" 
   (	"CRD_APPNO" VARCHAR2(20 BYTE), 
	"CRD_DEFAULTER" VARCHAR2(1 BYTE), 
	"CRD_COMMENT" LONG, 
	"CRD_LIABDATE" DATE
   ) 
------------------------------------------------------------
 --DDL for COM_CRDPROMOTERS
------------------------------------------------------------
CREATE TABLE "UBILAS1"."COM_CRDPROMOTERS" 
   (	"PROM_APPNO" VARCHAR2(20 BYTE), 
	"PROM_COMPNAME" VARCHAR2(100 BYTE), 
	"PROM_PROMNAME" VARCHAR2(100 BYTE), 
	"PROM_PROMADDRESS" VARCHAR2(500 BYTE), 
	"PROM_PROMPOSITION" VARCHAR2(50 BYTE)
   ) 
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------

------------------------------------------------------------
 --DDL for 
------------------------------------------------------------

------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------ 
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
------------------------------------------------------------
 --DDL for 
------------------------------------------------------------
drop table ADDITIONAL_PARAMETER;
drop table TERMSCOND;
drop table npamaster;
drop table post_disbursal;
drop table post_disbursaldetails_com;
drop table POSTDISBRULES;
drop table POSTDISBSIGNAL;
drop table COM_POSTDISBURSAL;
drop table FINACLETOLAPS_CCPC_DETAILS cascade constraints;
drop table FINACLETOLAPS_ONETIME_BILLS;
drop table FINACLETOLAPS_ONETIME_CCTLOD;
drop table FINACLETOLAPS_ONETIME_LC;
drop table LIMIT_MASTER;
drop table TEMP_MASTER;
drop table TEMP_CHILD;
drop table SUPPLIERDETAILS;
drop table SUBDOCUMENT_OLD1;
drop table STRESSRULEMAIN;
drop table RISKMGMTPER;
drop table RISKMGMTCOM;
drop table RESULTS;
drop table REPORTPROFILE;
drop table REPAYMENT;
drop table REHABILATIONVIEW;
drop table REHABILATION;
drop table LOS_NOTIFICATION;
drop table LOS_PROCESS;
drop table LOS_REMINDERS;
drop table LOS_SERVICE;
drop table LIMIT_REGISTER;
drop table APPAUDITORNOTES;
drop table APPAUDITORREMARKS;
drop table APP_HISTORY;
drop table APP_ENCLOSURES;
drop table BRANCH_REF_COMMENTS;
drop table COM_BANKING_DT_AUG13;
drop table COM_BANKING_DTAUG13;
drop table COM_BANKING_DT2;
drop table COM_BANKING_NEW;
drop table APPLICATION_DISPOSAL_REGISTER;
drop table FIN_ACTUALS;
drop table FIN_ESTIMATES;
drop table ODDEMOGRAPHICS;
drop table ODAPPLICATIONS;
drop table PER_POSTDISBURSEMENT;
drop table STATIC_VALUESET;
drop table STATIC_VALUE;

drop table SSI_STOCK;